### PR TITLE
faq page implemeted

### PR DESCRIPTION
**Pull request by sreechand2002**
## Issue that this pull request solves

 Closes: #39 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

ss

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @sreechand2002 the page is looking good and is working as expected. Can you please add a little enhancement here i.e

When we click on expand icon, footer of the page shifts down every time, can we please make this not happen after clicking on the expand icon. Also let's keep the footer only after `100vh` of the screen.

Please make these changes  and it will be good to go :)

**Comment by sreechand2002** [comment]
@Kajol-Kumari  i have made the requested changes can you review it now

**Review by Kajol-Kumari — APPROVED** [review]
Perfect! LGTM :+1: 

Just one suggestion,never make a PR using your `main` branch.

**Comment by Kajol-Kumari** [comment]
@all-contributors please add @sreechand2002  for code

**Pull request merged**
