### PR TITLE
Frontend fix team card

### PR DESCRIPTION
**Pull request by abhay313**
## Issue that this pull request solves

 Closes: #179 

## Proposed changes
fixed linkedin icon and removed linear gradient
## Types of changes
Now linkedin icon is visible by setting icon's `color: black;` and there is no effect of `linear-gradient`

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Screenshot from 2021-01-07 14-01-10

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by abhay313** [comment]
Due to hover linkedin icon is blue

**Review by salil-naik — APPROVED** [review]
Perfect! @abhay313 

Also, it's considered a bad practice to use `!important` in CSS. In future, as far as possible try to avoid using it. 

All the best.

**Comment by salil-naik** [comment]
@abhay313 are you a SWoC or DWoC participant?

**Comment by abhay313** [comment]
SWoC

**Pull request merged**
