### PR TITLE
Adding Validation resource form

### PR DESCRIPTION
**Pull request by garvitgupta13**
## Issue that this pull request solves

 Closes: [#504](https://github.com/HITK-TECH-Community/Community-Website/issues/504)

### Brief description of what is fixed or changed
I have added validation to the resource form.

Implemented email validation (Gives error on giving wrong mail)
Implemented URL validation (Gives error on giving wrong URL)
Implemented date validation (Gives error on giving date of incorrect date)
Required validation implemented on:
(I) Name
(ii) Email
(iii) Resource URL
(iv) Level of trust
(v) Date

I have used joi-browser for its implementation

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by garvitgupta13** [comment]
Please add the necessary labels of gssoc21.
Really happy that it has finally passed build check.

**Comment by Kajol-Kumari** [comment]
> Hey, @Kajol-Kumari this time I have created new branch and not pushed any changes in the package-lock.json.

Yes! that's what I was pointing to as that file had some hidden dependency from your local PC which was causing the trouble. Glad that you got it fixed :)

**Comment by garvitgupta13** [comment]
Thank you @Kajol-Kumari  for guiding me and helping me to solve this error.

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for your patience and hard-work :)

**Pull request merged**
