### PR TITLE
Added manage broadcasts page in admin dashboard

### PR DESCRIPTION
**Pull request by Aniket-508**
## Issue that this pull request solves

 Closes: #682 

### Brief description of what is fixed or changed
If logged in as admin, added manage broadcasts page to edit and delete broadcast by calling suitable api with the id being passed as a param.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

https://user-images.githubusercontent.com/71957423/156921287-3cbf20ff-5fcd-4c2c-bc69-d8f8dccbec14.mp4

### CODE REVIEW

**Comment by Aniket-508** [comment]
@Kajol-Kumari Please have a look at this.

**Comment by Aniket-508** [comment]
@Kajol-Kumari One more request please, can you please assign difficulty as Hard please, since I had to make a lot more changes  than expected and JWOC.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@Aniket-508 the deletion isn't happening correctly & also the number of cards isn't getting updated accordingly.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari It is, you can check the network requests and also after deletion, the api is called again which you can clearly see in the video attached.

The call is happening and it's giving 200 but the number of cards remains same. Maybe I will raise a separate issue to tackle this

**Review by Kajol-Kumari — APPROVED** [review]

**Comment by Aniket-508** [comment]
@Kajol-Kumari Can you please add hard instead of level3 as a label?

**Pull request merged**
