### PR TITLE
View broadcasts

### PR DESCRIPTION
**Pull request by nehaparmar99**
## Issue that this pull request solves
View broadcast Feature under DWOC and SWOC
 Closes: #312 

### Brief description of what is fixed or changed
The cards under all_broadcasts have been made flipable and on the other side of the card a view button has been added that opens up a modal and shows the whole broadcast message

_Put an `x` in the boxes that apply_

- [x] New feature (non-breaking change which adds functionality)

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Screenshot (304)
Screenshot (302)

### CODE REVIEW

**Comment by nehaparmar99** [comment]
@Kajol-Kumari please review and let me know if any changes are required :)

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @nehaparmar99 The feature looks fine. Just need a bit of enhancement:
1. You are using `react-card-flip` but I can't see any package.json file in this PR having that package
2. `view` button should show the details of the current card. Currently same content is displayed no matter which card's view button we click on.

GIF of issue:
flip_bug

**Comment by nehaparmar99** [comment]
> Hey @nehaparmar99 The feature looks fine. Just need a bit of enhancement:
> 
> 1. You are using `react-card-flip` but I can't see any package.json file in this PR having that package
> 2. `view` button should show the details of the current card. Currently same content is displayed no matter which card's view button we click on.
> 
> GIF of issue:
> flip_bug

I'll change that by evening👍I think I didn't commit the package.json file , I'll do that😅sorry for thay

**Comment by nehaparmar99** [comment]
> Hey @nehaparmar99 The feature looks fine. Just need a bit of enhancement:
> 
> 1. You are using `react-card-flip` but I can't see any package.json file in this PR having that package
> 2. `view` button should show the details of the current card. Currently same content is displayed no matter which card's view button we click on.
> 
> GIF of issue:
> flip_bug

Ma'am I've updated the modal, it now shows the details of the current card, and also updated package.json

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for incorporating the suggested changes @nehaparmar99 
LGTM :+1:

**Pull request merged**
