### PR TITLE
Updated Validations & Card UI

### PR DESCRIPTION
**Pull request by ShubhamSj07**
## Issue that this pull request solves

 Closes: #505 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
New_Card-UI

## Other information

Any other information that is important to this pull request
Also I had updated footer section sign up letter email validation's & updated git icon hover effect!

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @ShubhamSj07 Please resolve the conflict here

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , my updated code is not getting pushed! 
In above conflict it is showing older code with dark theme incoming changes..

While pushing getting this error

Err3

**Comment by Kajol-Kumari** [comment]
Hey @ShubhamSj07 as you have conflicts so until, you resolve them, you won't be able to push your changes. Can you please dm me on our slack or discord so that we can have a meet to resolve this?

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , pls check now..
I think now it should be gtg!

**Review by Kajol-Kumari — APPROVED** [review]
Hey @ShubhamSj07 The code now works fine just the indentation of the `footer section` code has broken a bit. I will fix that (Btw do install `preetier` extension in your code-editor, this will save your time for indenting :) )

**Comment by Kajol-Kumari** [comment]
Btw I am glad you were able to resolve the conflict @ShubhamSj07  :)
Keep Learning, All the best!!

**Comment by ShubhamSj07** [comment]
> Btw I am glad you were able to resolve the conflict @ShubhamSj07 :)
> Keep Learning, All the best!!

> Btw I am glad you were able to resolve the conflict @ShubhamSj07 :)
> Keep Learning, All the best!!

Thanks u for understanding me & actually I loved this amazing dark mode⚡

**Pull request merged**
