### PR TITLE
`Open Source Contributors` section added in About us page

### PR DESCRIPTION
**Pull request by vedikaag99**
## Issue that this pull request solves

 Closes: #607 (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Screen Shot 2021-04-10 at 7 43 45 PM
Screen Shot 2021-04-10 at 7 43 37 PM

## Other information

no

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @vedikaag99 the image list of the contributors seems a bit left aligned, instead, we want it to be centre aligned. Can you please fix it?
Also it seems a bit off for small screens, please fix that

**Comment by Kajol-Kumari** [comment]
Also please do the following -
1. Make the cursor to pointer, on-hover over the image. Onclick, we should be directed to our github's contribution graph

**Comment by vedikaag99** [comment]
> Hey @vedikaag99 the image list of the contributors seems a bit left aligned, instead, we want it to be centre aligned. Can you please fix it?
> Also it seems a bit off for small screens, please fix that

Hi @Kajol-Kumari yes, it seems a little left-aligned but it is because of the image itself. I'm attaching screenshots for reference.
Screen Shot 2021-04-11 at 4 40 10 PM
Screen Shot 2021-04-11 at 4 39 49 PM

What do I do in this case?

**Comment by vedikaag99** [comment]
> Also please do the following -
> 
> 1. Make the cursor to pointer, on-hover over the image.
> 2. Onclick, we should be directed to our github's contribution graph

done

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 for the image position fix, maybe you can give extra left margin so that it looks good as it's not looking good currently and if that will distort the UI. Maybe we can shift `our contributors` section under `Get Involved` page. WDYT?

**Comment by vedikaag99** [comment]
Screen Shot 2021-04-13 at 12 06 02 AM

For small screens:
Screen Shot 2021-04-13 at 12 05 42 AM
@Kajol-Kumari

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for the fix @vedikaag99 
LGTM 👍

**Pull request merged**
