### PR TITLE
auto-hide timer added (set to 3seconds)

### LINKED ISSUE #513: [Frontend] Toast should Disappear after a while
Deliverable -

- [ ] Currently, the toast remains there unless we explicitly close it, add a  timer (2-3 second maybe) after which the toast should disappear

### PR DESCRIPTION
**Pull request by ashuvssut**
closes #513 

----------------------------

_- I have participated in GSSOC_

### CODE REVIEW

**Comment by ashuvssut** [comment]
@Kajol-Kumari, didi, I have just reduced the auto-hide timer from 6000ms to 3000ms

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari, didi, I have just reduced the auto-hide timer from 6000ms to 3000ms

Just a minor update. After we click on close icon of the toast, i see a black border, can we please replace it with something better and consistent? (maybe make it white)

**Comment by ashuvssut** [comment]
which one should i keep?
1.  this one
image


OR

2. this one
image

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari, I ve removed the black outline
> 
> which one should i keep?
> 
> 1. this one (has white border and has that ripple effect when clicked)
>    image
> 
> OR
> 
> 1. this one ❤ this one (has no border, but, it has that ripple effect when clicked)
>    image

Let's keep the second one

**Comment by ashuvssut** [comment]
@Kajol-Kumari , done!

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Pull request merged**
