### PR TITLE
Fixed issues in login form - hiding password icon

### PR DESCRIPTION
**Pull request by Ohranj**
## Issue that this pull request solves

 Closes: #386

## Proposed changes
Changed your handler for inside the useEffect to use useRef and state to manage the hide password icon

### Brief description of what is fixed or changed
 - Hiding and showing password works each time
 - The cursor and icon color change on hover as needed
 - 
## Types of changes

_Put an `x` in the boxes that apply_

- [ x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information
Issues should now be resolved and working as you expect.

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @Ohranj just asking out of curosity. Why am I seeing the commit by @AlexDorrington in this PR?

**Comment by Ohranj** [comment]
I think that's my old Github page, it's somehow linked. I'll need to try and sort that out.

**Comment by Kajol-Kumari** [comment]
> I think that's my old Github page I had, it's somehow linked. I'll need to try and sort that out.

Okay, please fix the Conficts here so that we can merge this

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Comment by Kajol-Kumari** [comment]
Hey @Ohranj If you have made this PR under any program(swoc or dwoc) please let us know.

**Pull request merged**
