### PR TITLE
[Bug] Hide and Show button doesn't work until we refresh the page #314

### PR DESCRIPTION
**Pull request by kenkirito**
## Issue that this pull request solves

 Closes: #314

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by kenkirito** [comment]
@Kajol-Kumari check

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @kenkirito this doesn't seems to work.
Try adding the `onClick` event listener to the icon and handle it using the hide/show logic

**Comment by kenkirito** [comment]
@kenkirito ok

**Comment by Kajol-Kumari** [comment]
@kenkirito can you please provide an update on this PR?

**Comment by kenkirito** [comment]
Working on it

**Comment by ashuvssut** [comment]
Hi @kenkirito! refer [this](https://github.com/HITK-TECH-Community/Community-Website/pull/379/commits/4143cc45e15a22ca21e9f22b8e31a3cc57d4c1b9). this is how i resolved this issue by moving a particular piece of logic into  `useEffect`. learn use of `useEffect` hook. By learning hooks you will be able to tackle such issues in no time 😄😄.

**Comment by AnjaliPatle** [comment]
Hey @kenkirito , can you please provide an update for this PR?

**Comment by ashuvssut** [comment]
this issue was fixed by #379.

**Pull request closed without merging**
