### PR TITLE
Added Welcome Bot config file

### PR DESCRIPTION
**Pull request by musavveer**
Closes: #148

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
```
  Hello there!👋 Welcome to the project!🚀⚡
  Thank you and congrats🎉 for opening your very first issue in this project. Community-website aims to build a resource sharing platform in order to reduce the knowledge gap. Please adhere to our [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md).🙌
Please make sure not to start working on the issue, unless you get assigned to it.😄
   
  Feel free to join our [Slack Community](https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-jgr1sd87-lhiXHO_x63Kt7h8VBxDaFw).💖 We have different channels for active discussions.✨ Hope you have a great time there!😄

``` 

Hey @musavveer This is a demo message for `new issue` welcome bot comment. Please make similar legit and meaningful messages for `new PR` opening and `first PR` merge.

**Comment by musavveer** [comment]
> ```
>   Hello there!👋 Welcome to the project!🚀⚡
>   Thank you and congrats🎉 for opening your very first issue in this project. Community-website aims to build a resource sharing platform in order to reduce the knowledge gap. Please adhere to our [Code of Conduct](https://github.com/HITK-TECH-Community/Community-Website/blob/main/code_of_conduct.md).🙌
> Please make sure not to start working on the issue, unless you get assigned to it.😄
>    
>   Feel free to join our [Slack Community](https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-jgr1sd87-lhiXHO_x63Kt7h8VBxDaFw).💖 We have different channels for active discussions.✨ Hope you have a great time there!😄
> ```
> 
> Hey @musavveer This is a demo message for `new issue` welcome bot comment. Please make similar legit and meaningful messages for `new PR` opening and `first PR` merge.

Okay

**Comment by musavveer** [comment]
I'm unable to send a PR to the existing one.
So, shall I send a new PR

**Comment by musavveer** [comment]
@Kajol-Kumari I have made the changes.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
LGTM :+1:

**Comment by Kajol-Kumari** [comment]
@all-contributors please add @musavveer for documentation

**Pull request merged**
