### PR TITLE
Updated  join-us.module.scss

### PR DESCRIPTION
**Pull request by kashi-verma**
changed the color of join us section

## Issue that this pull request solves

 Closes: #813 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
@kashi-verma  i would like to understand what updation u are intended to make?

**Comment by kashi-verma** [comment]
I've changed background color of join us section

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
can you provide a better color in dark mode as well?

**Comment by kashi-verma** [comment]
> can you provide a better color in dark mode as well?

Ohk , i do it

**Comment by kashi-verma** [comment]
Yes, I can.

**Comment by Kajol-Kumari** [comment]
closing this as duplicate

**Pull request closed without merging**
