### PR TITLE
 Broadcast Page for Admin

### PR DESCRIPTION
**Pull request by nehaparmar99**
## Issue that this pull request solves

 Closes: #354 
**Made under DWOC and SWOC**
### Brief description of what is fixed or changed
The broadcasts page now contains two cards 1. Add a new broadcast 2. Manage Broadcasts
Add a new broadcast opens up a text-editor where the admin can write a new broadcast.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] New feature (non-breaking change which adds functionality) 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Add a new Broadcast card
Screenshot (310)

Above on hover
Screenshot (309)

Screenshot (313)

EDITOR
Screenshot (314)

### CODE REVIEW

**Comment by nehaparmar99** [comment]
@Kajol-Kumari please review

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@nehaparmar99 please do the following:
1. Rename `editor` component to `add_broadcasts` component
2. Make the cards on `Broadcast` age appear side by side, instead of one upon other
3. Please use css-module instead of css file in the new coponent
4. Make the route path `/add_broadcast` instead of `editor` in app.js

**Comment by nehaparmar99** [comment]
> @nehaparmar99 please do the following:
> 
> 1. Rename `editor` component to `add_broadcasts` component
> 2. Make the cards on `Broadcast` age appear side by side, instead of one upon other
> 3. Please use css-module instead of css file in the new coponent
> 4. Make the route path `/add_broadcast` instead of `editor` in app.js

Ok, I'll do it by evening 👍
Any changes in the styling ?

**Comment by nehaparmar99** [comment]
@Kajol-Kumari made the following changes :
1.editor component renamed to add_broadcasts component
2.cards on Broadcast age appear side by side, except for on mobile view theyre stacked
3.css-module made .
4.Changed the routes
Screenshot (317)

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @nehaparmar99 please change the `broadcast.css` file to css-module as well. Rest looks good to go!

**Comment by nehaparmar99** [comment]
> Hey @nehaparmar99 please change the `broadcast.css` file to css-module as well. Rest looks good to go!

I thought that was done in another issue😅

**Comment by nehaparmar99** [comment]
> Hey @nehaparmar99 please change the `broadcast.css` file to css-module as well. Rest looks good to go!

@Kajol-Kumari ive done it!Please check.

**Review by Kajol-Kumari — APPROVED** [review]

**Pull request merged**
