### PR TITLE
Sass for privacy n resource page

### LINKED ISSUE #418: Refactoring Privacy_policy & Resource component
Refactoring the `Privacy Policy` and `Resource` as per the [proposed style](https://github.com/HITK-TECH-Community/Community-Website/blob/main/frontend/PROPOSAL.md). 

Note- Please make sure to follow all the guidelines mentioned in the proposed style properly!

### PR DESCRIPTION
**Pull request by ashuvssut**
## Issue that this pull request solves

close #418 

# Info
I have found that there are around 8 or 10 styles class names in those scss file which are not at all used by any component/element
If you want me to point them out, then please ask. I will point out all of them in review

---------------

_--I have participated in DWoC n SWoC_

### CODE REVIEW

**Comment by ashuvssut** [comment]
@salil-naik @Kajol-Kumari If this PR gets merged today, then please assign me the other issue 416.

I will submit another PR today only.

**Comment by salil-naik** [comment]
@ashuvssut I guess someone changed the folder name from `Navbar` to `navbar` and that is giving an error during compilation. Please look into it.

**Review by salil-naik — CHANGES_REQUESTED** [review]
Hi. You will see `// Pages` as a comment in `app.js`. Please import all the page there.

**Comment by ashuvssut** [comment]
> @ashuvssut I guess someone changed the folder name from `Navbar` to `navbar` and that is giving an error during compilation. Please look into it.

image
But i cant see `navbar`. I have `Navbar` in this branch `ashuvssut:sass-privacy/resource`

try pulling again this tym
--- in git ref `pull/{ID}/head` you must have typed wrong ID

try again:
`git fetch origin pull/425/head && git checkout FETCH_HEAD`

**Comment by ashuvssut** [comment]
> Hi. You will see `// Pages` as a comment in `app.js`. Please import all the page there.

done

**Comment by ashuvssut** [comment]
⚠⚠⚠

Please do not merge this PR. merge #426 first

I just realized that the imports for buttons need to be implemented the right way. The directory of button.jsx has changed in #426. I will update this PR wrt #426.

for now review #426 and suggest changes/corrections (if any). after that gets merged successfully...I will update this one accordingly

**Comment by ashuvssut** [comment]
@Kajol-Kumari I ve resolve the merge conflicts. please review this one

**Review by Kajol-Kumari — APPROVED** [review]
Nice and Clean!

**Comment by Kajol-Kumari** [comment]
Hey @ashuvssut If there is redundant classnames in css-modules. Feel free to remove them all and come up with a PR. we will review and accept it, if found feasible :)

**Pull request merged**
