### PR TITLE
Shift after hovering on `admin?` button #280

### PR DESCRIPTION
**Pull request by kenkirito**
## Issue that this pull request solves

 Closes: #280 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by kenkirito** [comment]
@Kajol-Kumari done changes in navebar.css

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@kenkirito why do we need changes in `carousel.css`?

**Comment by kenkirito** [comment]
@Kajol-Kumari please view the changes in navebar. Css

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari please view the changes in navebar. Css

Remove the unnecessary changes from this PR

**Comment by kenkirito** [comment]
Ok

**Pull request closed without merging**
