### PR TITLE
[ Backend ]Create Get Testimonial API

### PR DESCRIPTION
**Pull request by shivamgaur99**
Closes: #1024 

Get Testimonial API to fetch testimonials from the database. 

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

image

### CODE REVIEW

**Comment by shivamgaur99** [comment]
@Kajol-Kumari please review and let me know if any changes required

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Comment by shivamgaur99** [comment]
@Kajol-Kumari Can I create separate issues for the POST, UPDATE, and DELETE APIs in the backend?

**Comment by Kajol-Kumari** [comment]
@shivamgaur99 Testimonials can be directly entered by admins so create and delete API will be required and will be good to be integrated on the admin panel.

**Comment by shivamgaur99** [comment]
@Kajol-Kumari Can I create the issue ?

**Comment by Kajol-Kumari** [comment]
yes, for create and delete please feel free to create, also we will need frontend issues for integrating it to admin dashboard, i will create them if you don't get time

**Pull request merged**
