### PR TITLE
join us form enhanced

### PR DESCRIPTION
**Pull request by vedikaag99**
## Issue that this pull request solves

 Closes: #337 (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
Screen Shot 2021-02-06 at 5 44 41 PM

## Other information

Any other information that is important to this pull request
This PR is under DWoC.

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 please make the checkbox list row-wise, similar to `year of study`

**Comment by vedikaag99** [comment]
Screen Shot 2021-02-07 at 3 21 56 PM
Is this okay? @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> Screen Shot 2021-02-07 at 3 21 56 PM
> Is this okay? @Kajol-Kumari

Looks good! Try putting the option `poster Designing`  just after `Video editing` so that it can fit in the row and look better.

**Comment by vedikaag99** [comment]
Screen Shot 2021-02-08 at 12 26 27 PM
done @Kajol-Kumari please review now.

**Comment by Kajol-Kumari** [comment]
Hey @vedikaag99 can you please fix the `submit` button size and `year of Study` section?

**Comment by vedikaag99** [comment]
> Hey @vedikaag99 can you please fix the `submit` button size and `year of Study` section?

What needs to be fixed for the `year of Study` section?

**Comment by chait04** [comment]
just my thinking : I think, There is a little bit more space between checkbox and text . Under the year of study

**Comment by vedikaag99** [comment]
Screen Shot 2021-02-09 at 12 01 02 AM
@Kajol-Kumari done

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@vedikaag99 please fix the width of `submit`. Rest looks good to me

**Comment by vedikaag99** [comment]
> @vedikaag99 please fix the width of `submit`. Rest looks good to me

Do I make it even smaller ? @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> > @vedikaag99 please fix the width of `submit`. Rest looks good to me
> 
> Do I make it even smaller ? @Kajol-Kumari

It's width is appearing too small. we need to keep the same width as it was before.

**Comment by vedikaag99** [comment]
Screen Shot 2021-02-09 at 2 11 04 PM
Do i increase it even further? @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> Screen Shot 2021-02-09 at 2 11 04 PM
> Do i increase it even further? @Kajol-Kumari

It's not appearing this way when I tested this PR. Can you please check if you have the latest pull?

**Comment by vedikaag99** [comment]
@Kajol-Kumari Ah sorry! I wasn't working on the latest pull. Well now I have pulled the latest changes but I am having some trouble in pushing my code. Hence I am closing this PR and opening a new one. Sorry for the inconvenience caused!

**Pull request closed without merging**
