### PR TITLE
Allow client to get team members details

### PR DESCRIPTION
**Pull request by hazemessam**
## Issue that this pull request solves

 Closes: #723

## Proposed changes

- Allow getting team member details by its id.
- Add test for getting team member details.
- Allow getting all team members.
- Add test for getting all team members.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Comment by hazemessam** [comment]
@Kajol-Kumari

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@hazemessam can we please handle the db exceptions correctly. similar to [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/faq/getFaq.js)

**Comment by hazemessam** [comment]
> @hazemessam can we please handle the db exceptions correctly. similar to [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/faq/getFaq.js)

Ok, but what is the problem with the way that I handled it with?

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Comment by Kajol-Kumari** [comment]
> > @hazemessam can we please handle the db exceptions correctly. similar to [this](https://github.com/HITK-TECH-Community/Community-Website/blob/main/backend/app/routes/faq/getFaq.js)
> 
> Ok, but what is the problem with the way that I handled it with?

We wanted to see proper message [if there is a db issue, `internal error` doesn't give clarity so we are moving this way to handle the errros

**Pull request merged**
