### PR TITLE
`admin ?`  button enhanced for DWoC

### PR DESCRIPTION
**Pull request by vedikaag99**
## Issue that this pull request solves

 Closes: #297 (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
Screen Shot 2021-01-26 at 3 18 42 PM
when the admin button is active, its active link has same styling as hover effects as per requirement in the issue.

Screen Shot 2021-01-26 at 3 20 00 PM
when the admin button is not active

Screen Shot 2021-01-26 at 3 18 57 PM
For small screens, on hover the white background has been removed.

## Other information

Any other information that is important to this pull request
no

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
For small screens as well the button's text color should be white

**Comment by vedikaag99** [comment]
> For small screens as well the button's text color should be white

The text color is white only. Just on hover, it becomes blue. Should I change make it white even for hover?

**Comment by Kajol-Kumari** [comment]
> > For small screens as well the button's text color should be white
> 
> The text color is white only. Just on hover, it becomes blue. Should I make it white even for hover? @Kajol-Kumari

Yeah, let's keep it same as what we have for large screens on hover

**Comment by vedikaag99** [comment]
Screen Shot 2021-01-26 at 4 53 14 PM

@Kajol-Kumari done.

**Review by Surajbokde — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
LGMT :+1:

**Pull request merged**
