### PR TITLE
Fix Update Broadcast Modal Description Population and Refactor form for Styling Consistency

### PR DESCRIPTION
**Pull request by shivamgaur99**
Closes: #1045 

**Refactor update broadcast functionality to handle approval status and ensure style consistency**

- Modify update logic to correctly handle both approved and non-approved broadcast items.
- Refactor form components to maintain consistent styling between create and update interfaces.
- Ensure SunEditor content population and styling options align across broadcast editing workflows.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
image

### CODE REVIEW

**Comment by shivamgaur99** [comment]
@Kajol-Kumari Changes done please review

**Comment by shivamgaur99** [comment]
@Kajol-Kumari could you please check ?

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@shivamgaur99 
1. The earlier change included the classes for dark and light mode which has been completely removed in this pr
2. After successful update the toast message is saying `successfully approved` which is wrong, it should have been `successfully updated` instead.

**Comment by shivamgaur99** [comment]
> 1. The earlier change included the classes for dark and light mode which has been completely removed in this pr
> 2. After successful update the toast message is saying `successfully approved` which is wrong, it should have been `successfully updated` instead.

@Kajol-Kumari both changes done

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@shivamgaur99 the dark and light mode seems to be messed up in this pr, check the https://deploy-preview-1061--hitk-tech-community.netlify.app/ and compare it with https://hitk-tech-community.netlify.app/

**Comment by shivamgaur99** [comment]
Hi @Kajol-Kumari its working fine can you check it again and please send ss if you are seeing any different
image
image

**Comment by shivamgaur99** [comment]
i check more than 10 times by switching dark mode and light mode its showing same

**Comment by shivamgaur99** [comment]
image
image
please look

**Comment by shivamgaur99** [comment]
image

**Review by Kajol-Kumari — APPROVED** [review]
changes doesn't seem to impact other pages ui but not sure why deploy preview is misbehaving, approving the pr for now

**Comment by shivamgaur99** [comment]
> changes doesn't seem to impact other pages ui but not sure why deploy preview is misbehaving, approving the pr for now

thank you so much

**Comment by Kajol-Kumari** [comment]
reverted the pr as merging this actually messed up the dark and light mode theme

**Comment by shivamgaur99** [comment]
@Kajol-Kumari Can you tell me why its happening, while i have'nt change others file, may be after some times it will okay

**Comment by Kajol-Kumari** [comment]
multiple reason can add to it
1. Your forked branch is outdated
2. the props that you passed is getting passed by reference
3. any un-intenteded change which will required debugging. And i already checked by merging, something is definately off in the pr which disturbed the ui of whole website

**Pull request merged**
