### PR TITLE
Admin-LoginPage Responsive Issue Fixed

### PR DESCRIPTION
**Pull request by ShubhamSj07**
## Issue that this pull request solves

 Closes: #601 

## Proposed changes
Made Admin Login Page Consistent.
Both Image & Form Responsiveness Issues Fixed!

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Login_HITK-Issue_FIXED

### CODE REVIEW

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , pls review

**Review by Kajol-Kumari — APPROVED** [review]
Hey @ShubhamSj07 thanks for the quick fix. THis LGTM :+1: 

Can I expect a follow up PR containing the fix for `forgot your password` page? [ I am not opening up any issue for the same. You directly come up with the PR ]

Please let me know if that's fine for you

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , sure why not

**Comment by ShubhamSj07** [comment]
@Kajol-Kumari , sure why not
will fix that issue at earliest

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari , sure why not
> will fix that issue at earliest
> So, should i make issue & start working for same?

Hey @ShubhamSj07 you can directly come up with the PR. NO need to open up a separate issue for this.

**Pull request merged**
