### PR TITLE
Fixed checkbox of join us form for small screen(#562)

### PR DESCRIPTION
**Pull request by akshitakanojia**
## Issue that this pull request solves

 Closes: #562 

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

Screenshot 2021-03-26 225534

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @akshitakanojia The checkbox looks good but radio buttons seems kinds distorted now. Can you please fix them for small screen sizes

**Comment by akshitakanojia** [comment]
> Hey @akshitakanojia The checkbox looks good but radio buttons seems kinds distorted now. Can you please fix them for small screen sizes. You can take the reference of `Resource Sharing Form` for reference

@Kajol-Kumari  both of them looks almost the same 😅
img1

img2

can you please suggest what change is needed

**Comment by akshitakanojia** [comment]
Got it, you are talking about labels. I'll fix this.

**Review by Kajol-Kumari — APPROVED** [review]
Thank you for the quick fix @akshitakanojia 
LGTM :+1:

**Pull request merged**
