### PR TITLE
Join us form validation

### PR DESCRIPTION
**Pull request by garvitgupta13**
## Issue that this pull request solves

 Closes: #506 

### Brief description of what is fixed or changed
Used joi-browser to handle the form validation

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by garvitgupta13** [comment]
I created a new branch this time, but I don't know why is it showing my previous commits also. Really sorry for that.

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 thanks for quickly fixing it. For the dark theme for multi-select you can overridding the class of `multiselect` component based on the theme or you can try once [this](https://stackoverflow.com/questions/63635017/react-native-multi-select-change-select-text-color) see if any of these works for you and let me know.

**Comment by garvitgupta13** [comment]
Dark Theme:
image
Light Theme
image

**Comment by garvitgupta13** [comment]
Hey, @Kajol-Kumari please let me know these changes are fine.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @garvitgupta13 can you please push the dark theme changes? 
Also that black scroll kind of thing appear in the multi-select box, can we please remove it?

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 can you please push the dark theme changes?
> Also that black scroll kind of thing appear in the multi-select box, can we please remove it?

Mam, I tried to best to remove of that scroll, but in the [documentation](https://www.npmjs.com/package/react-multi-select-component) there is no method defined for it. And the scroll looks fine in firefox. I guess it might be some browser issue
FireFox:
image

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Comment by garvitgupta13** [comment]
The changes are not reflcted in webpage
image

**Pull request merged**
