### PR TITLE
[Frontend] The Broadcast isn't appearing in correct format Fixed

### LINKED ISSUE #946: [Frontend] The Broadcast isn't appearing in correct format
##Description

- [ ] The broadcast description should have appeared in formatted view, instead i am seeing html tags in it.
- [ ] The link button on the details page doesn't take to the linked page

## Expectation
- The broadcast detail page should show the formatted text instead of `<p>`, <br>` or any html tag.
- when clicked on link button, it should open the resource link in a new tab. The current data contains the resourceLink but clicking on it doesn't direct us to the expected page.

Screenshot 2024-05-21 at 10 12 14 PM
Screenshot 2024-05-21 at 10 12 25 PM
Screenshot 2024-05-21 at 10 15 07 PM

### PR DESCRIPTION
**Pull request by Hemu21**
## Issue that this pull request solves

[Issue Link](https://github.com/HITK-TECH-Community/Community-Website/issues/946) resolve #946 
 Closes: #946 

### Brief description of what is fixed or changed

- The broadcast description should have appeared in formatted view, instead i am seeing html tags in it. Fixed now it appears in formatted view.
- The link button on the details page doesn't take to the linked page Fixed. Now it redirects to the linked page.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Comment by Hemu21** [comment]
@Kajol-Kumari  when you get a free time, can you please check and merge it.

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Screenshot 2024-05-23 at 6 06 27 PM
The card is still showing unformatted data and link button is still not opening the link value coming in broadcast detail

**Comment by Hemu21** [comment]
@Kajol-Kumari  please check the preview deploy here.  I think you checking in main website.

**Comment by Kajol-Kumari** [comment]
@Hemu21 check the all broadcasts page once

**Comment by Hemu21** [comment]
@Kajol-Kumari  sorry i checked only boardcasts page i doesn't checked all boardcast page. now updated can you please check.

**Review by Kajol-Kumari — APPROVED** [review]

**Pull request merged**
