### PR TITLE
Broadcast admin frontend

### PR DESCRIPTION
**Pull request by ashuvssut**
## Issue that this pull request solves

 Closes: #401

## Tasks done
- [x] The `manage broadcast` should take to the page of all broadcasts
- [x] All the broadcasts should have a delete icon that should allow the admin to delete a broadcast

## Info

Currently the icons look distorted like this. I can solve it by overriding a css property that is globally defined. But, we are shifting to use css-modules. therefore i didn't add my css to override that globally defined css.
image

to see how it looks when that global css is removed see the image below:
image

----------------

_--I have participated in DWoC n SWoC_

### CODE REVIEW

**Comment by ashuvssut** [comment]
I think The GH action workflow to add a reviewer is not working. There is no one assigned as a reviewer in this PR😕

**Review by AnjaliPatle — APPROVED** [review]
LGTM 👍
@Kajol-Kumari a background has been added behind the edit and delete icons. Please review it.

**Comment by Kajol-Kumari** [comment]
Hey @ashuvssut I don't see the deletion is happening temporarily as mentioned in the issue. Also the broadcast page seems distorted a bit. It would be great if you can fix that.

**Comment by ashuvssut** [comment]
Oh... I thought that you wanted the frontend only (i mean the button icon)
I will do that no problem

I will check where is the distorted part.

**Comment by ashuvssut** [comment]
@Kajol-Kumari I ve added the delete function

@Kajol-Kumari if you see any discrepancy this time.. then a screenshot ll be really helpful😄😄. Actually I could not find that distortion that you were talking about.

But, I aligned those cards in the center. those cards were looking odd getting aligned to the left.

**Review by Kajol-Kumari — APPROVED** [review]
Nice and Clean!
LGTM :+1:

**Pull request merged**
