### PR TITLE
Converted CSS Files to CSS modules- SECTION 7

### PR DESCRIPTION
**Pull request by nehaparmar99**
## Issue that this pull request solves

 Closes: #349 
Done under DWOC and SWOC
## Types of changes

_Put an `x` in the boxes that apply_
- [x] New feature (non-breaking change which adds functionality)

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @nehaparmar99 few of the buttons are getting disorted i,e `Sign In` button , `Join Us` button, `Submit` button on `contact-us` page. Can you please fix the,

**Comment by nehaparmar99** [comment]
@Kajol-Kumari I have added the css classes of the button in each of the files individually😅is that fine?I couldn't find another way to make that work.😅

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I have added the css classes of the button in each of the files individuallyis that fine?I couldn't find another way to make that work.

Can't we directly convert button to module and just add the css there and for rest just import that module and use the class?

**Comment by nehaparmar99** [comment]
> > @Kajol-Kumari I have added the css classes of the button in each of the files individuallyis that fine?I couldn't find another way to make that work.
> 
> Can't we directly convert button to module and just add the css there and for rest just import that module and use the class? You can take reference from #364 How she has imported the motive module in `carousel.js` and used it.

Okay sure I'll do that👍

**Comment by nehaparmar99** [comment]
@Kajol-Kumari  you'll be merging this PR right?

**Comment by tejan-singh** [comment]
@nehaparmar99 This pr is creating merge conflicts. Please resolve all conflicts.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari you'll be merging this PR right?

Yes! Once you resolve the conflicts and do the requested changes. We would test and merge it :)

**Comment by Kajol-Kumari** [comment]
Hey @nehaparmar99 can you please provide an update on this.

**Comment by nehaparmar99** [comment]
> Hey @nehaparmar99 can you please provide an update on this.

I'll update it by evening, I'm working on it.
Also one more question, the updated code has navbar.scss file, so should I leave it like that?

**Comment by Kajol-Kumari** [comment]
> > Hey @nehaparmar99 can you please provide an update on this.
> 
> I'll update it by evening, I'm working on it.
> Also one more question, the updated code has navbar.scss file, so should I leave it like that?

Hey @nehaparmar99 please leave the `navbar` folder as it is and make the required changes for the rest

**Pull request closed without merging**
