### PR TITLE
Admin Dashboard Bug

### PR DESCRIPTION
**Pull request by sakshikhachane**
## Issue that this pull request solves

 Closes: #430 

### Brief description of what is fixed or changed
Fixed the bug.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and it passes all the current test cases.

HITK-Tech-Community-Google-Chrom

### CODE REVIEW

**Comment by sakshikhachane** [comment]
@Kajol-Kumari Please review the PR.

**Comment by Kajol-Kumari** [comment]
Hey @sakshikhachane this issue has been fixed under [this](https://github.com/HITK-TECH-Community/Community-Website/pull/435 PR only but acknowledging your work and as this PR solves the issue as well I would give you score for this under swoc. but can't merge this. as it will just create redundancy.

**Comment by sakshikhachane** [comment]
@Kajol-Kumari Okay no problem. It won't get counted in DWOC right?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Okay no problem. It won't get counted in DWOC right?

yeah 'coz I won't be able to merge this.

**Review by Kajol-Kumari — APPROVED** [review]

**Pull request closed without merging**
