### PR TITLE
Updated resource page

### LINKED ISSUE #247: Enhancement in Resource sharing page
Deliverables:

- [ ] Make the top margin small, same as `contact-us` page
- [ ] Change the pencil icon with the same icon being used in `contact-us` page
- [ ] The calender icon should also have the hovering effect and cursor pointer
- [ ] Replace the `level of trust` checkbox with select box having the placeholder of `level of trust`
- [ ] Put the `valid until` text under input box only

### PR DESCRIPTION
**Pull request by urvashi-code1255**
## Issue that this pull request solves
SWOC AND DWOC PARTICIPANT
Closes #247 

## Proposed changes

-  Make the top margin small, same as contact-us page
-  Change the pencil icon with the same icon being used in contact-us page
- The calender icon should also have the hovering effect and cursor pointer
- Replace the level of trust checkbox with select box having the placeholder of level of trust
- Put the valid until text under input box only

### Brief description of what is fixed or changed
1. Made the margin same as of the contact us page.
2. Pencil icon is changed.
3. calender icon has cursor pointer and orange color on hover.
4.  Added select box.
5. Added the valid until text under input box only

## Types of changes
Bootstrap, Css, Javascript

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari Old PR was creating mess for me, so i opened this one. I have pushed the changes. Please check..

**Comment by AnjaliPatle** [comment]
Hey @urvashi-code1255 the screenshots look great! Just a few minor changes: 

1. Please change the pencil icon in the "Additional Info" text-box, so that it will be the same as the one in "Your Subject" text-box in the Contact-Us page. 

icon

2. The select box UI is not responsive right now. Please adjust the styling to make it responsive for smaller screens.

responsive

3. In `frontend/src/components/resource/resources.js` in the input tag at `line 94` kindly make the following small changes:
    - Remove `placeholder="Date"`.
    - Add `name="dob"` .

tag

**Review by AnjaliPatle — CHANGES_REQUESTED** [review]
Hey @urvashi-code1255 the screenshots look great! Just a few minor changes: 

1. Please change the pencil icon in the "Additional Info" text-box, so that it will be the same as the one in "Your Subject" text-box in the Contact-Us page. 

icon

2. The select box UI is not responsive right now. Please adjust the styling to make it responsive for smaller screens.

responsive

3. In `frontend/src/components/resource/resources.js` in the input tag at `line 94` kindly make the following small changes:
    - Remove `placeholder="Date"`.
    - Add `name="dob"` .

tag

**Comment by urvashi-code1255** [comment]
Sorry, I haven't checked for responsiveness. I have made it responsive upto 400px and done all the requested changes :)

**Comment by Kajol-Kumari** [comment]
> Sorry, I haven't checked for responsiveness. I have made it responsive upto 400px now and done all the requested changes :)

Hey @urvashi-code1255 can we please have the `level of trust` section one below the other for small screen i.e the title should be on the top row and all the radio button options below it.

**Comment by urvashi-code1255** [comment]
Sure @Kajol-Kumari !!

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari changes added.

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for incorporating the suggested changes @urvashi-code1255 
LGTM :+1:

**Pull request merged**
