### PR TITLE
Home page design

### PR DESCRIPTION
**Pull request by Muskan10Mehta**
## Issue that this pull request solves

 Closes: # 2

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Screenshot (154)
Screenshot (155)

##Other Information 

Figma link: https://www.figma.com/file/WsNOQVd5eG2c5xblSnRgfe/HomePage?node-id=0%3A1

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @Muskan10Mehta nice start, you you please try adding all the sections in figma that we have currently. Also if there is anything else that you think we can put on our homepage, feel free to add it in th edesign

**Comment by Muskan10Mehta** [comment]
Can You please give me a roughh idea of other sections that you currently have?

**Comment by Kajol-Kumari** [comment]
> Can You please give me a roughh idea of other sections that you currently have?

Hey @Muskan10Mehta Currently we have, Overview, Motive and About us section. you can always look at the homepage by runing the project's frontend :)

**Comment by jackfrost13** [comment]
@Muskan10Mehta Closing due to prolonged inactivity

**Pull request closed without merging**
