### PR TITLE
Fixed misaligned carousel buttons

### PR DESCRIPTION
**Pull request by Shridhar-dev**
## Issue that this pull request solves

 Closes: # (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey  @Shridhar-dev Thanks for opening up the PR. I request you to please provide related GIF or screenshot of the fix introduced through this PR.

**Comment by Shridhar-dev** [comment]
> Hey @Shridhar-dev Thanks for opening up the PR. I request you to please provide related GIF or screenshot of the fix introduced through this PR.

aligned
The arrow buttons of the carousel were not properly aligned with its dark blue background i.e they were not vertically centered properly

**Comment by Kajol-Kumari** [comment]
> > Hey @Shridhar-dev Thanks for opening up the PR. I request you to please provide related GIF or screenshot of the fix introduced through this PR.
> 
> aligned
> The arrow buttons of the carousel were not properly aligned with its dark blue background i.e they were not vertically centered properly

Hey @Shridhar-dev the current buttons looks good to me. Also the changes in this PR are not at all related to the carousel as I can see the changes in footer and `about us` page

**Comment by Shridhar-dev** [comment]
The screenshot is of the fixed view

**Pull request closed without merging**
