### PR TITLE
Home Top Section Responsiveness

### PR DESCRIPTION
**Pull request by sanjay270899**
## Issue that this pull request solves

 Closes: #448 

## Proposed changes
Improved Home Top Section Responsiveness

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshot
image

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @sanjay270899 the logo is getting very large for xl screens. Please fix that ASAP

**Comment by sanjay270899** [comment]
> Hey @sanjay270899 the logo is getting very large for xl screens. Please fix that ASAP

@Kajol-Kumari Can you please mention size in pixels?

**Comment by Kajol-Kumari** [comment]
> > Hey @sanjay270899 the logo is getting very large for xl screens. Please fix that ASAP
> 
> @Kajol-Kumari Can you please mention size in pixels?

You can refer [this](https://screensiz.es/xps-13)

**Comment by sanjay270899** [comment]
@Kajol-Kumari XL mean Google Pixel XL?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari XL mean Google Pixel XL?

By XL, I mean extra large screen resolution. Large screen resolution is generally (1366x768) and for extra large screens you can take it 1920×1080

**Comment by sanjay270899** [comment]
@Kajol-Kumari Open the inspect tool and tell me in which range Logo is large according to you?

image

**Comment by sanjay270899** [comment]
> > @Kajol-Kumari XL mean Google Pixel XL?
> 
> By XL, I mean extra large screen resolution. Large screen resolution is generally (1366x768) and for extra large screens you can take it 1920×1080

I haven't changed anything for large screen.

**Comment by Kajol-Kumari** [comment]
> > > @Kajol-Kumari XL mean Google Pixel XL?
> > 
> > 
> > By XL, I mean extra large screen resolution. Large screen resolution is generally (1366x768) and for extra large screens you can take it 1920×1080
> 
> I haven't changed anything for large screen.

Yes, Can see that in your code. I just tried zooming out my scree. But yes, if try putting the resolution under responsive tab, seems to work fine.

**Review by Kajol-Kumari — APPROVED** [review]

**Pull request merged**
