### PR TITLE
Badge for ExpressJS updated

### PR DESCRIPTION
**Pull request by LeeRenJie**
## Issue that this pull request solves

This is a small tweak to the readme.md. I am under DWOC

### Brief description of what is fixed or changed
Added logo for expressJS in tech stack

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
Updated badge for ExpressJS
image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @LeeRenJie can we please use some different background color as the express logo isn't clear currently

**Comment by LeeRenJie** [comment]
> Hey @LeeRenJie can we please use some different background color as the express logo isn't clear currently

Sure, I'll do a quick fix.

**Comment by LeeRenJie** [comment]
> Hey @LeeRenJie can we please use some different background color as the express logo isn't clear currently

image

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for quick update @LeeRenJie 
LGTM :+1:

**Pull request merged**
