### PR TITLE
Resources UI fixed

### PR DESCRIPTION
**Pull request by carbseater**
## Issue that this pull request solves

 Closes: #224  (issue number)

### Brief description of what is fixed or changed
 Resources section UI is fixed(added icons and some styling)
## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x ] Other (please describe): 
- It basically improves the UI of resources page as suggested .

## Checklist

_Put an `x` in the boxes that apply_

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
Capture
I have added 
1. Icons in input boxes
2. hovering effect on icons
3. cursor pointer
4. input box-shadow
5. input background color changes to white on click

## Other information
 
No

### CODE REVIEW

**Comment by carbseater** [comment]
I think I made a mistake. I didn't knew about branches, I tried to solve Resources UI and made a PR last night succesfully. But in this morning I was solving the ISSUES_TEMPLATES and i solved it succesfully but without changing the branches and commit it to my same main branch which showed up changes in this PR. Basically I solved both the issues #224 and #229  but in the same PR of issue #224. What should I do now . @Kajol-Kumari

**Comment by vrushti-mody** [comment]
> ## Issue that this pull request solves
> Closes: #224 (issue number)
> 
> ## Proposed changes
> ### Brief description of what is fixed or changed
> Resources section UI is fixed(added icons and some styling)
> 
> ## Types of changes
> _Put an `x` in the boxes that apply_
> 
> * [ ]  Bugfix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  Documentation update (Documentation content changed)
> * [x ] Other (please describe):
> * It basically improves the UI of resources page as suggested .
> 
> ## Checklist
> _Put an `x` in the boxes that apply_
> 
> * [x ] My code follows the style guidelines of this project
> * [x ] I have performed a self-review of my own code
> * [ x] I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings
> * [x ] My changes does not break the current system and it passes all the current test cases.
> 
> ## Screenshots
> Please attach the screenshots of the changes made in case of change in user interface
> Capture
> I have added
> 
> 1. Icons in input boxes
> 2. hovering effect on icons
> 3. cursor pointer
> 4. input box-shadow
> 5. input background color changes to white on click
> 
> ## Other information
> No

The PR looks good, could you just increase the width of the name and phone number to 100?
Also, 

> ## Issue that this pull request solves
> Closes: #224 (issue number)
> 
> ## Proposed changes
> ### Brief description of what is fixed or changed
> Resources section UI is fixed(added icons and some styling)
> 
> ## Types of changes
> _Put an `x` in the boxes that apply_
> 
> * [ ]  Bugfix (non-breaking change which fixes an issue)
> * [ ]  New feature (non-breaking change which adds functionality)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]  Documentation update (Documentation content changed)
> * [x ] Other (please describe):
> * It basically improves the UI of resources page as suggested .
> 
> ## Checklist
> _Put an `x` in the boxes that apply_
> 
> * [x ] My code follows the style guidelines of this project
> * [x ] I have performed a self-review of my own code
> * [ x] I have commented my code, particularly in hard-to-understand areas
> * [ ]  I have made corresponding changes to the documentation
> * [x]  My changes generate no new warnings
> * [x ] My changes does not break the current system and it passes all the current test cases.
> 
> ## Screenshots
> Please attach the screenshots of the changes made in case of change in user interface
> Capture
> I have added
> 
> 1. Icons in input boxes
> 2. hovering effect on icons
> 3. cursor pointer
> 4. input box-shadow
> 5. input background color changes to white on click
> 
> ## Other information
> No

Hey! Your PR looks good.
There are just two changes
1. Reduce the font of submit button in mobile-view
2. 2. In mobile view, there is a lot of padding for the trust level of the resource (1-5). Reduce that so that all the checkboxes fit in one line.
Make these changes and I'll merge your PR

**Comment by vrushti-mody** [comment]
> I think I made a mistake. I didn't knew about branches, I tried to solve Resources UI and made a PR last night succesfully. But in this morning I was solving the ISSUES_TEMPLATES and i solved it succesfully but without changing the branches and commit it to my same main branch which showed up changes in this PR. Basically I solved both the issues #224 and #229 but in the same PR of issue #224. What should I do now . @Kajol-Kumari

I think its fine. I'll add the points for both the issues, don't worr

**Comment by carbseater** [comment]
> > ## Issue that this pull request solves
> > Closes: #224 (issue number)
> > ## Proposed changes
> > ### Brief description of what is fixed or changed
> > Resources section UI is fixed(added icons and some styling)
> > ## Types of changes
> > _Put an `x` in the boxes that apply_
> > 
> > * [ ]   Bugfix (non-breaking change which fixes an issue)
> > * [ ]   New feature (non-breaking change which adds functionality)
> > * [ ]   Breaking change (fix or feature that would cause existing functionality to not work as expected)
> > * [ ]   Documentation update (Documentation content changed)
> > * [x ] Other (please describe):
> > * It basically improves the UI of resources page as suggested .
> > 
> > ## Checklist
> > _Put an `x` in the boxes that apply_
> > 
> > * [x ] My code follows the style guidelines of this project
> > * [x ] I have performed a self-review of my own code
> > * [ x] I have commented my code, particularly in hard-to-understand areas
> > * [ ]   I have made corresponding changes to the documentation
> > * [x]   My changes generate no new warnings
> > * [x ] My changes does not break the current system and it passes all the current test cases.
> > 
> > ## Screenshots
> > Please attach the screenshots of the changes made in case of change in user interface
> > Capture
> > I have added
> > 
> > 1. Icons in input boxes
> > 2. hovering effect on icons
> > 3. cursor pointer
> > 4. input box-shadow
> > 5. input background color changes to white on click
> > 
> > ## Other information
> > No
> 
> The PR looks good, could you just increase the width of the name and phone number to 100?
> Also,
> 
> > ## Issue that this pull request solves
> > Closes: #224 (issue number)
> > ## Proposed changes
> > ### Brief description of what is fixed or changed
> > Resources section UI is fixed(added icons and some styling)
> > ## Types of changes
> > _Put an `x` in the boxes that apply_
> > 
> > * [ ]   Bugfix (non-breaking change which fixes an issue)
> > * [ ]   New feature (non-breaking change which adds functionality)
> > * [ ]   Breaking change (fix or feature that would cause existing functionality to not work as expected)
> > * [ ]   Documentation update (Documentation content changed)
> > * [x ] Other (please describe):
> > * It basically improves the UI of resources page as suggested .
> > 
> > ## Checklist
> > _Put an `x` in the boxes that apply_
> > 
> > * [x ] My code follows the style guidelines of this project
> > * [x ] I have performed a self-review of my own code
> > * [ x] I have commented my code, particularly in hard-to-understand areas
> > * [ ]   I have made corresponding changes to the documentation
> > * [x]   My changes generate no new warnings
> > * [x ] My changes does not break the current system and it passes all the current test cases.
> > 
> > ## Screenshots
> > Please attach the screenshots of the changes made in case of change in user interface
> > Capture
> > I have added
> > 
> > 1. Icons in input boxes
> > 2. hovering effect on icons
> > 3. cursor pointer
> > 4. input box-shadow
> > 5. input background color changes to white on click
> > 
> > ## Other information
> > No
> 
> Hey! Your PR looks good.
> There are just two changes
> 
> 1. Reduce the font of submit button in mobile-view
> 2. 1. In mobile view, there is a lot of padding for the trust level of the resource (1-5). Reduce that so that all the checkboxes fit i

**Comment by carbseater** [comment]
> > I think I made a mistake. I didn't knew about branches, I tried to solve Resources UI and made a PR last night succesfully. But in this morning I was solving the ISSUES_TEMPLATES and i solved it succesfully but without changing the branches and commit it to my same main branch which showed up changes in this PR. Basically I solved both the issues #224 and #229 but in the same PR of issue #224. What should I do now . @Kajol-Kumari
> 
> Hey! I am sorry but you will have to create 2 separate PRs if you want to be scored for both. Try revoking the new commits and switch to a new branch and make a PR

Okay I am making two separate PR for this. Thanks

**Comment by vrushti-mody** [comment]
> > > I think I made a mistake. I didn't knew about branches, I tried to solve Resources UI and made a PR last night succesfully. But in this morning I was solving the ISSUES_TEMPLATES and i solved it succesfully but without changing the branches and commit it to my same main branch which showed up changes in this PR. Basically I solved both the issues #224 and #229 but in the same PR of issue #224. What should I do now . @Kajol-Kumari
> > 
> > 
> > Hey! I am sorry but you will have to create 2 separate PRs if you want to be scored for both. Try revoking the new commits and switch to a new branch and make a PR
> 
> Okay I am making two separate PR for this. Thanks

Add me as the reviewer for both of them. I'll check them locally and merge them 😄

**Comment by carbseater** [comment]
> > > > I think I made a mistake. I didn't knew about branches, I tried to solve Resources UI and made a PR last night succesfully. But in this morning I was solving the ISSUES_TEMPLATES and i solved it succesfully but without changing the branches and commit it to my same main branch which showed up changes in this PR. Basically I solved both the issues #224 and #229 but in the same PR of issue #224. What should I do now . @Kajol-Kumari
> > > 
> > > 
> > > Hey! I am sorry but you will have to create 2 separate PRs if you want to be scored for both. Try revoking the new commits and switch to a new branch and make a PR
> > 
> > 
> > Okay I am making two separate PR for this. Thanks
> 
> Add me as the reviewer for both of them. I'll check them locally and merge them

Tagging you in the PR's is enough for adding you as reviewer or something else ? @vrushti-mody

**Pull request closed without merging**
