### PR TITLE
feat: show contactus data on admin dashboard

### PR DESCRIPTION
**Pull request by iMADi-ARCH**
## Issue that this pull request solves

 Closes: #740 

## Proposed changes
Display the contactus data as fetched from `/getContactUs` endpoint.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
image

## Other information

**Note: ** delete functionality has not been implemented on the backend as of creating this PR and thus this doesn't include the same.

### CODE REVIEW

**Comment by thevirengarg** [comment]
@iMADi-ARCH Please explain changes you made and add necessary screenshots.

**Comment by iMADi-ARCH** [comment]
@thevirengarg The logic and ui is the same as of the joinus page.
I fetch the data from the endpoint `/getContactUs` and display it as cards.
The styling of the card is same as in joinus so as to maintain consistency.

**Comment by iMADi-ARCH** [comment]
Also the Reply button has a mailto link so as to facilitate replying to the messages.

**Comment by Aditi-Dahiya** [comment]
> @thevirengarg The logic and ui is the same as of the joinus page. I fetch the data from the endpoint `/getContactUs` and display it as cards. The styling of the card is same as in joinus so as to maintain consistency.

@iMADi-ARCH , Can you please keep the colors used consistent and not include multiple colors? Specifically, Red color seems to go off. Rest is great.

**Comment by iMADi-ARCH** [comment]
@Aditi-Dahiya 
image

Are these good? sorry I am not very good at choosing colors 😓

**Comment by Aditi-Dahiya** [comment]
> @Aditi-Dahiya 
> image
> 
> Are these good? sorry I am not very good at choosing colors 😓 

Okay so for now you can replace the red color with the pink tone used throughout the website.

**Comment by iMADi-ARCH** [comment]
@Aditi-Dahiya 
image

**Comment by Aditi-Dahiya** [comment]
> @Aditi-Dahiya 
> image
> 

Yeah, good for now 👍🏻

**Review by thevirengarg — COMMENTED** [review]
@iMADi-ARCH First, You need to get the issue assigned to you and then make a PR.

**Review by thevirengarg — COMMENTED** [review]
Go to the issue and comment on it so I can assign it you and then I will review this PR.

**Comment by iMADi-ARCH** [comment]
> @iMADi-ARCH First, You need to get the issue assigned to you and then make a PR.

#740 has no more assignment tag
image

**Comment by thevirengarg** [comment]
> > @iMADi-ARCH First, You need to get the issue assigned to you and then make a PR.
> 
> #740 has no more assignment tag image

Just ignore it, comment on it then i will assign it to you

**Comment by iMADi-ARCH** [comment]
> > > @iMADi-ARCH First, You need to get the issue assigned to you and then make a PR.
> > 
> > 
> > #740 has no more assignment tag image
> 
> Just ignore it, comment on it then i will assign it to you

i did just now.

**Comment by Shreyas-SAS** [comment]
Please assign him the issue and process the review as per repository workflow of accepting PRs.

**Review by Aditi-Dahiya — CHANGES_REQUESTED** [review]
Styling issues to be addressed before merging.

**Comment by iMADi-ARCH** [comment]
> improve the styling of the cards which should resonate with the website's theme and also add some comments in your code. It is advisable to add screenshots of before and after in your PR description while making improvements to the UI .

Every page in dashboard has almost the same card styling which is what i have followed. Also there should have been a common card component and the button component is also being exported as Button1, Button2, Button3 etc which does not makes much sense. Maybe an issue should be opened to refactor some of the styling.

image
image
image

I will add comments to the code.

**Review by thevirengarg — COMMENTED** [review]
@iMADi-ARCH Everything is fine, just add some comments.

**Review by Aditi-Dahiya — APPROVED** [review]

**Review by thevirengarg — APPROVED** [review]

**Pull request merged**
