### PR TITLE
[Fixed bugs] Refactor AddFaq page replace react-tag-input 

### PR DESCRIPTION
**Pull request by shivamgaur99**
Closes: #944 

Here are the key changes:

**Functional Components**: I've refactored the class component into functional components to make the code more concise and readable.
**Enhanced Tags Management:** Implemented a more intuitive approach for adding and removing tags, enhancing the user experience.

Put an `x` in the boxes that apply.

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

Put an `x` in the boxes that apply.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x]  My changes does not break the current system and it pass all the current test cases.

## Screenshots
image
image

## Other information

Any other information that is important to this pull request?

### CODE REVIEW

**Comment by shivamgaur99** [comment]
@Kajol-Kumari Please review, i take reference from the `addbrodcasts` for tags input and also convert the class component to functional component.

And should we use the textarea tag for the answer input field? if any changes required, let me know

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
1. the manage faq, is giving error, please fix it.
2. The cursor should change to pointer, if i click on `cross` icon to remove the tag, check the image below - 
Screenshot 2024-05-26 at 7 04 48 PM

**Comment by shivamgaur99** [comment]
> 1. the manage faq, is giving error, please fix it.
> 2. The cursor should change to pointer, if i click on `cross` icon to remove the tag, check the image below -
> 
> Screenshot 2024-05-26 at 7 04 48 PM

changes done

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Pull request merged**
