### PR TITLE
Replace class with className #178

### PR DESCRIPTION
**Pull request by kenkirito**
closes #182 
## Issue that this pull request solves

standardize the code 

### Brief description of what is fixed or changed

changes class name to class

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

HITK Tech Community and 49 more pages - Personal - Microsoft​ Edge 05-01-2021 02_26_05 PM

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @kenkirito please fill the PR template properly including the PR numbers

**Comment by kenkirito** [comment]
ok

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Comment by Kajol-Kumari** [comment]
@kenkirito can you please tell me if you are taking part in SWOC as well?

**Comment by kenkirito** [comment]
yes i am

**Comment by Kajol-Kumari** [comment]
cool, please fill the PR template so that I can merge this :)

**Comment by kenkirito** [comment]
done

**Comment by Kajol-Kumari** [comment]
@kenkirito always add `closes #<issue number>` in the PR template so that it closes the linked issue as soon as the PR gets merged :)

**Pull request merged**
