### PR TITLE
logo

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Himanshu
LOGO SUBMISSIONS

## It have created additional folder where LOGOs can be saved

 Closes: # (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
hey @himanshu007-creator please make the folder name `logo` also please put your logo design under that folder.

**Comment by himanshu007-creator** [comment]
ok mam

**Comment by himanshu007-creator** [comment]
mam can you tell how can i upload image in folder?

**Comment by himanshu007-creator** [comment]
Himanshu

**Pull request closed without merging**
