### PR TITLE
Integrate broadcast page with backend

### PR DESCRIPTION
**Pull request by garvitgupta13**
## Issue that this pull request solves

 Closes: #644 

### Brief description of what is fixed or changed
Fetched data from DB and populated it on the frontend of `all-broadcast` and `broadcast` page

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
image
image
image

Currently there is no image because [demo image URL](http://imageurl@imageurl.com/) doesn't contains any image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari if you want me to remove test data from `/broadcast` page than please let me know

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@garvitgupta13 can you please do the following -
1. Provide a video/gif of the feature that you tested on local[I need to check if the search and filter option is working fine]
2. Console.log statements can't be removed where-ever not required. For ex- [here](https://github.com/HITK-TECH-Community/Community-Website/pull/650/files#diff-1395dc29e3395ffd57c9132759415a96d7b9ace95a9c4dd1c95290656d11c560R63)
3. I believe, you nee dto edit the view modal as well in order to make the complete data apear on opening the dialog box of the broadcasts [please include it in the above video/gif]

**Comment by garvitgupta13** [comment]
> @garvitgupta13 can you please do the following -
> 
> 1. Provide a video/gif of the feature that you tested on local[I need to check if the search and filter option is working fine]
> 2. Console.log statements can't be removed where-ever not required. For ex- [here](https://github.com/HITK-TECH-Community/Community-Website/pull/650/files#diff-1395dc29e3395ffd57c9132759415a96d7b9ace95a9c4dd1c95290656d11c560R63)
> 3. I believe, you need to edit the view modal as well in order to make the complete data appear on opening the dialog box of the broadcasts [please include it in the above video/gif]

1. Currently only the tags filter is working, I tried to take months, year, input from the dropdown but that is not working. All the broadcasts have the same tags `tags: (3) ["tag1", "tag2", "tag3"]` that's why you might have observed no such difference but tags filter is working perfectly

https://user-images.githubusercontent.com/70805691/118848698-9c5c0100-b8ec-11eb-88ae-7110fa5c77dd.mp4

2. I will remove the log statements in next commit.

3. Card.jsx
```
const [data, setData] = useState({});
  const handleOpen = (s, h, i) => {
    setOpen(true);
    setData({ head: h, desc: s, img: i });
  };

return (
    <div id={props.id} className={style["card-container"]}>
      <Modals theme={dark} open={open} handleClose={handleClose} data={data} />
.
.
.
```
The main data is stored in `dataa` array and this is not passed as props to models.
We have passed only `data` object to modal and it is set to correct data.


On each API call, I am getting this printed on the backend. There was no such log before, now only I have observed it.
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.header (E:\Community-Website\backend\node_modules\express\lib\response.js:771:10)
    at ServerResponse.json (E:\Community-Website\backend\node_modules\express\lib\response.js:264:10)
    at errorHandler (E:\Community-Website\backend\helpers\error.js:15:30)
    at Layer.handle_error (E:\Community-Website\backend\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (E:\Community-Website\backend\node_modules\express\lib\router\index.js:315:13)
    at E:\Community-Website\backend\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (E:\Community-Website\backend\node_modules\express\lib\router\index.js:335:12)
    at Immediate.next (E:\Community-Website\backend\node_modules\express\lib\router\index.js:275:10)
    at Immediate._onImmediate (E:\Community-Website\backend\node_modules\express\lib\router\index.js:635:15)
    at processImmediate (internal/timers.js:464:21)
```
I am getting this after I switched to node `14.17.0` before this I was using node `12.16.2`

**Comment by jackfrost13** [comment]
@garvitgupta13 for 1, can you add a few broadcast with different tags and then check if that helps

**Comment by garvitgupta13** [comment]
> @garvitgupta13 for 1, can you add a few broadcast with different tags and then check if that helps

Please let me know once you have added them

**Comment by jackfrost13** [comment]
> > @garvitgupta13 for 1, can you add a few broadcast with different tags and then check if that helps
> 
> Please let me know once you have added them

I would rely on you to add those and check if it works as expected :)
You can leverage the existing codebase(tests) for that

**Comment by garvitgupta13** [comment]
> > > @garvitgupta13 for 1, can you add a few broadcast with different tags and then check if that helps
> > 
> > 
> > Please let me know once you have added them
> 
> I would rely on you to add those and check if it works as expected :)
> You can leverage the existing codebase(tests) for that

Could you help me how to do that, I don't have much idea of the backend

**Comment by jackfrost13** [comment]
@Kajol-Kumari is create broadcast integrated with backend?

**Comment by garvitgupta13** [comment]
> @Kajol-Kumari is create broadcast integrated with backend?

As far as I know adding broadcast page PR is under review and is not integrated with backend
@Kajol-Kumari please correct me if I am wrong

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari is create broadcast integrated with backend?

NO, we haven't integrated it till now.

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari let me know if further anymore changes are to be done in this PR

**Pull request merged**
