### PR TITLE
loader added in manage admin

### PR DESCRIPTION
**Pull request by dhwaj1902**
## Issue that this pull request solves

 Closes: #595

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @dhwaj1902 thanks for introducing the idea of loader. But the way loader is appearing isn't good. Please make it appear on the top of the page. Maybe something like below :arrow_down: 
loader

**Comment by dhwaj1902** [comment]
Please Check, I have updated the Loader.

**Comment by Kajol-Kumari** [comment]
> Please Check and review, I have updated the Loader.
> 

Perfect! Looks good to go!

**Review by Kajol-Kumari — APPROVED** [review]
Looks nice and clean!
Thanks for incorporating the suggested changes @dhwaj1902

**Pull request merged**
