### PR TITLE
Refactor Footer and GetInvolved Components

### PR DESCRIPTION
**Pull request by sanjay270899**
## Issue that this pull request solves

 Closes: #416 

## Proposed changes
Changed the Component Structure as proposed style.

### Brief description of what is fixed or changed

- Changed the `module.css` to `module.scss`.
- Moved `GetInvolved` to `Pages` folder.
- Renamed the classes and files names as proposed.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (changed structure as proposed): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

1. Footer
image

2. GetInvolved
image

### CODE REVIEW

**Comment by tejan-singh** [comment]
- Nav Bar for responsive site seems to get distorted. Please correct the position.
Capture

**Comment by sanjay270899** [comment]
@tejan-singh My task was to refactor `Footer` and `GetInvolved` Components. I haven't touched `NavBar` Component. You can check in `Files Changed` option.
There is already a PR for fixing it (#447)

**Review by tejan-singh — APPROVED** [review]
Okey @sanjay270899.

**Comment by Kajol-Kumari** [comment]
@sanjay270899 Can you please let us know if you are SWoC participant as well?

**Pull request merged**
