### PR TITLE
New Resource Page

### PR DESCRIPTION
**Pull request by urvashi-code1255**
## Issue that this pull request solves

 Closes: #276 

## Proposed changes
-  Remove the Phone no. field from the resource sharing form.
-  Make the calender icon's by-default color same as other icons
-  Make the radio button fill color same as linear gradient color used for border of input field on click.

### Brief description of what is fixed or changed
-  Removed the Phone no. field from the resource sharing form.
-  I made the calender icon's by-default color same as other icons
-  I made the radio button fill color same as linear gradient color used for border of input field on click.

## Types of changes
CSS, Javascript, Bootstrap 4.

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Please attach the screenshots of the changes made in case of change in user interface
Capture

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari Please check this PR. I did a mistake in that PR that I took older branch and did changes in that one only. I will take care from next time and make a new branch and will work on it. Sorry for the inconvinience

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @urvashi-code1255 please reduce the padding between radio button and it's respective labels or make it like `level of trust` in one line and all the options in the next line

**Comment by urvashi-code1255** [comment]
Capture

Is this Okay @Kajol-Kumari ?

**Comment by Kajol-Kumari** [comment]
> Capture
> 
> Is this Okay @Kajol-Kumari ?

Can we keep the title left aligned? It would look consistent @urvashi-code1255

**Comment by urvashi-code1255** [comment]
So should I make title left aligned for all the screen sizes? @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> So should I make title left aligned for all the screen sizes? @Kajol-Kumari

Yes

**Comment by urvashi-code1255** [comment]
Capture
Like this?

Capture
Or like this? @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> Capture
> Like this?
> 
> Capture
> Or like this? @Kajol-Kumari

@urvashi-code1255 please keep it same as the first one

**Comment by Kajol-Kumari** [comment]
@mohit355 please test this PR

**Comment by mohit355** [comment]
> @mohit355 please test this PR

ok

**Comment by Kajol-Kumari** [comment]
@urvashi-code1255 please mention in the PR under which programs you have made this Pr

**Review by Kajol-Kumari — APPROVED** [review]
Nice and clean!
LGMT :+1:

**Comment by urvashi-code1255** [comment]
I am DWOC and SWOC participant @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
> I am DWOC and SWOC participant @Kajol-Kumari

Please mention it in the `other information` section of the PR description. It would be easy to track :)

**Pull request merged**
