### PR TITLE
Resource page

### PR DESCRIPTION
**Pull request by urvashi-code1255**
## Issue that this pull request solves

 Closes: #276 

## Proposed changes
-  Remove the Phone no. field from the resource sharing form.
-  Make the calender icon's by-default color same as other icons
-  Make the radio button fill color same as linear gradient color used for border of input field on click.

### Brief description of what is fixed or changed
-  Removed the Phone no. field from the resource sharing form.
-  I made the calender icon's by-default color same as other icons
-  I made the radio button fill color same as linear gradient color used for border of input field on click.

## Types of changes
CSS, Javascript, Bootstrap 4.

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Please attach the screenshots of the changes made in case of change in user interface
Capture

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
This PR contains a lot of unnecessary changes, please remove them

**Review by Kajol-Kumari — COMMENTED** [review]
Hey @urvashi-code1255 try `git checkout HEAD -- my-file.txt` for reverting the changes as manually doing so won't revert it. For reference, checkout [this](https://stackoverflow.com/questions/7147270/hard-reset-of-a-single-file)

**Comment by urvashi-code1255** [comment]
@Kajol-Kumari  I did `git checkout HEAD -- my-file.txt ` Please check now.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I did `git checkout HEAD -- my-file.txt ` Please check now.

I hope you replaced the `my-file.txt` with the respective file names as I can still see all the unwanted changes in this PR

**Pull request closed without merging**
