### PR TITLE
Broadcast Page Design

### PR DESCRIPTION
**Pull request by amanprateek123**
## Issue that this pull request solves
The UI issue of broadcast page
 Closes: #53 

## Proposed changes
Implementing the design for Broadcast page.

### Brief description of what is fixed or changed
1. Adding the multi carousel(slider) for the broadcast.
2. Adding the popup after clicking any broadcast card.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe):Implementing UI 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
Screenshot from 2021-01-06 17-04-52
Screenshot from 2021-01-06 21-02-57

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@amanprateek123 please do the following changes:
1. Revert/Remove the `faq` related changes from this PR. (`faq.css` and `faq.png` file)
2. The ellipses(...) shouldn't be done manually, instead when the text size goes beyond the size of the card, make it break in the form of ellipses
3. The model is appearing same for each card, instead it should show the content of the card which is being clicked.

Screenshot from 2021-01-07 12-20-41

**Comment by amanprateek123** [comment]
@Kajol-Kumari  Ok Got it!!

**Comment by Kajol-Kumari** [comment]
> @amanprateek123 please do the following changes:
> 
> 1. Revert/Remove the `faq` related changes from this PR. (`faq.css` and `faq.png` file)
> 2. The ellipses(...) shouldn't be done manually, instead when the text size goes beyond the size of the card, make it break in the form of ellipses
> 3. The model is appearing same for each card, instead it should show the content of the card which is being clicked.
> 
> Screenshot from 2021-01-07 12-20-41

Hey @amanprateek123 let's not make all these changes in this PR only as it would become too large. Please resolve the conflict, we will merge this and I will open up a new issue for the changes I suggested you in here

**Comment by amanprateek123** [comment]
@Kajol-Kumari  Got it. I will solve the conflicts.But please assign that new issue to me.

**Comment by amanprateek123** [comment]
@Kajol-Kumari  please review this PR again and tell me that everything is fine or not(regarding conflicts)

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Got it. I will solve the conflicts.But please assign that new issue to me.

Sure @amanprateek123 !

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Comment by amanprateek123** [comment]
@Kajol-Kumari  please open the new issue and assign to me(regarding updates in broadcast page)

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari please open the new issue and assign to me(regarding updates in broadcast page)

@amanprateek123 please claim [this](https://github.com/HITK-TECH-Community/Community-Website/issues/234)

**Pull request merged**
