### PR TITLE
Send Contact Us Form Response to Admins

### PR DESCRIPTION
**Pull request by rohithmsr**
## Issue that this pull request solves

 Closes: #499 

### Brief description of what is fixed or changed

Contact Us Model to store the response of the users is created and as soon as the user sends the response, an email is sent
to the admins following a template mentioned in utility folder.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
------------

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by jackfrost13** [comment]
@yadvi12 On what basis you are merging PR's?

**Comment by rohithmsr** [comment]
May i know why have you reverted the commit? @jackfrost13

**Comment by yadvi12** [comment]
> @yadvi12 On what basis you are merging PR's?

will check it again

**Comment by jackfrost13** [comment]
> May i know why have you reverted the commit? @jackfrost13

Hi, yes I am definitely answerable to you.
I believe the merge was done by @yadvi12 without proper feedback, hence I had to revert it,
Can you please raise a fresh PR for it?

**Comment by rohithmsr** [comment]
Sure !
@jackfrost13

**Pull request merged**
