### PR TITLE
BUGS FIXED TAGS ARE NOT GETTING SAVED IN DATABASE

### PR DESCRIPTION
**Pull request by dhyaneshsiddhartha15**
## Issue that this pull request solves

Closes: #928

### Brief description of what is fixed or changed

- Fixed the issue where tags were not being saved correctly in the backend.
- Updated the `question.js` model to ensure that the `tags` field is correctly defined as an array of strings.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes do not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

*No UI changes were made.*

## Other information

Any other information that is important to this pull request:

- Ensured that tags are now correctly handled and stored as an array of strings in the MongoDB database.
- Added logging for better debugging and tracking of tag data.
-Please Review and Merge  @Kajol-Kumari

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
@dhyaneshsiddhartha15  can you please add some recording showing that its working now?

**Comment by dhyaneshsiddhartha15** [comment]
> @dhyaneshsiddhartha15 can you please add some recording showing that its working now?
Yeah Sure but its working though

**Comment by Kajol-Kumari** [comment]
> @dhyaneshsiddhartha15 can you please add some recording showing that its working now?

@dhyaneshsiddhartha15  any update on this?

**Comment by dhyaneshsiddhartha15** [comment]
> > @dhyaneshsiddhartha15 can you please add some recording showing that its working now?
> 
> @dhyaneshsiddhartha15 any update on this?
Yeah working on it as there are couples of bugs coming too

**Pull request closed without merging**
