### PR TITLE
[Backend] Added error handlers to add team

### PR DESCRIPTION
**Pull request by vinrusty**
## Issue that this pull request solves

 Closes: #766 

## Proposed changes
-> Added error handler to handle errors while saving the data to the database while adding a team member.

### Brief description of what is fixed or changed
-> Added error handler to handle errors while saving the data to the database while adding a team member.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request
## Consider this for GSSOC'22

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@vinrusty  Below is the sample payload that we are sending from frontend.
```
{full_name: "Test_Kajol",…}
description: "This is the dummy User"
full_name: "Test_Kajol"
github_url: "https://github.com/kajol-kumari"
image: "PNG\r\n\u001a\n\u0000\u0000\u0000\rIHDR\u0000\u0
linkedin_url: "https://www.linkedin.com/in/kajol-kumari-73245b166"
teams: ["Open Source", "Broadcast", "Design", "Social", "Resource Sharing"]
0: "Open Source"
1: "Broadcast"
2: "Design"
3: "Social"
4: "Resource Sharing"
twitter_url: "https://twitter.com/_Kajol_singh_"
```

Please modify the api so that It accepts this payload as right now, it's breaking.

**Comment by vinrusty** [comment]
> @vinrusty Below is the sample payload that we are sending from frontend.
> 
> ```
> {full_name: "Test_Kajol",…}
> description: "This is the dummy User"
> full_name: "Test_Kajol"
> github_url: "https://github.com/kajol-kumari"
> image: "�PNG\r\n\u001a\n\u0000\u0000\u0000\rIHDR\u0000\u0
> linkedin_url: "https://www.linkedin.com/in/kajol-kumari-73245b166"
> teams: ["Open Source", "Broadcast", "Design", "Social", "Resource Sharing"]
> 0: "Open Source"
> 1: "Broadcast"
> 2: "Design"
> 3: "Social"
> 4: "Resource Sharing"
> twitter_url: "https://twitter.com/_Kajol_singh_"
> ```
> 
> Please modify the api so that It accepts this payload as right now, it's breaking.

@Kajol-Kumari I think the reason its breaking is because the terms in the payload does not match with the terms in the backend.
I had converted for example "full_name" into "fullName" when I was correcting ESlint errors so in the payload if you give send terms in camel cases it might work.

**Comment by vinrusty** [comment]
Please label this PR as GSSOC'22

**Comment by Kajol-Kumari** [comment]
> Please label this PR as GSSOC'22

Can you please update this branch as it contains unnecessary changes related to Resources

**Pull request merged**
