### PR TITLE
Refactored all broadcasts page

### PR DESCRIPTION
**Pull request by FireQueen-3010**
## Issue that this pull request solves

Part of issue #490 (broadcasts page - all broadcasts) 

## Types of changes

_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] My changes does not break the current system and it passes all the current test cases.

## Screenshots

1) Increased box-shadow of cards:
image
2) Changed hover to click to flip cards:
image
3) Changed animation transitions on hover:
https://user-images.githubusercontent.com/59244300/111776470-0f8acc00-88d8-11eb-834d-92cf58d1c7ff.mp4
4) Made a subtle change on button on broadcast card:
image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please do review my pr @Kajol-Kumari

**Comment by FireQueen-3010** [comment]
Fixed package-lock.json as well @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Hey @FireQueen-3010 The changes looks good to me. Can you please try improving the search box on the `All Broadcasts` page

**Comment by FireQueen-3010** [comment]
Ok!

**Comment by FireQueen-3010** [comment]
Done with the changes, do check @Kajol-Kumari :)

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for incorporating the suggested changes @FireQueen-3010 
LGTM :+1:

**Pull request merged**
