### PR TITLE
1)Removed unwanted hover effects from card in about section. 2)Added …

### PR DESCRIPTION
**Pull request by Shridhar-dev**
…a better box shadow effect and transition timing on hover to the cards in the about section. 3) Changed the text 'by students,for students' in about section from having h4 to h5 for better readability. 4)Fixed the colour of the copyright footer. 5)Fixed the email form and signup button in the footer.

## Issue that this pull request solves

 Closes: # (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@Shridhar-dev These enhacements looks nice. Please do the following changes:
1. Make the emailId input box and submit button of the footer having `border-radius:8px` and add a horizontal line(having width smaller than the upper horizontal line) of `#016795` this color above the copyright text

**Comment by Shridhar-dev** [comment]
Will surely do the necessary changes

**Comment by Shridhar-dev** [comment]
> @Shridhar-dev These enhacements looks nice. Please do the following changes:
> 
> 1. Make the emailId input box and submit button of the footer having `border-radius:8px` and add a horizontal line(having width smaller than the upper horizontal line) of `#016795` this color above the copyright text
> 2. Don't remove the hovering effect in `about-us` page. If you can find better hover color, apply that

Which hover effect do you mean? The one that the card gets after getting hovered?

**Comment by Kajol-Kumari** [comment]
> > @Shridhar-dev These enhacements looks nice. Please do the following changes:
> > 
> > 1. Make the emailId input box and submit button of the footer having `border-radius:8px` and add a horizontal line(having width smaller than the upper horizontal line) of `#016795` this color above the copyright text
> > 2. Don't remove the hovering effect in `about-us` page. If you can find better hover color, apply that
> 
> Which hover effect do you mean? The one that the card gets after getting hovered?

Yes, in `about-us` page when you hover on the cards

**Comment by Shridhar-dev** [comment]
> > > @Shridhar-dev These enhacements looks nice. Please do the following changes:
> > > 
> > > 1. Make the emailId input box and submit button of the footer having `border-radius:8px` and add a horizontal line(having width smaller than the upper horizontal line) of `#016795` this color above the copyright text
> > > 2. Don't remove the hovering effect in `about-us` page. If you can find better hover color, apply that
> > 
> > 
> > Which hover effect do you mean? The one that the card gets after getting hovered?
> 
> Yes, in `about-us` page when you hover on the cards

Done!

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@Shridhar-dev just revert the `copyright` section style as It was looking better previously. Rest looks good to go

**Comment by Shridhar-dev** [comment]
> @Shridhar-dev just revert the `copyright` section style as It was looking better previously. Rest looks good to go

Reverted

**Review by Kajol-Kumari — COMMENTED** [review]
Hey @Shridhar-dev please apply the same background-color `#016795` as it was previously for the copyright section. Also the UI is getting distorted a bit for smaller screens, please fix it.

Screenshot from 2021-01-02 20-17-57

**Comment by Shridhar-dev** [comment]
> Hey @Shridhar-dev please apply the same background-color `#016795` as it was previously for the copyright section. Also the UI is getting distorted a bit for smaller screens, please fix it.
> 
> Screenshot from 2021-01-02 20-17-57

Changes are made!

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for incorporating the suggested changes @Shridhar-dev 
LGTM :+1:

**Comment by Kajol-Kumari** [comment]
@all-contributors please add @Shridhar-dev for code

**Comment by Shridhar-dev** [comment]
Thanks 😀

**Pull request merged**
