### PR TITLE
Fixing validation resource form

### PR DESCRIPTION
**Pull request by garvitgupta13**
## Issue that this pull request solves

 Closes: [#504](https://github.com/HITK-TECH-Community/Community-Website/issues/504)

### Brief description of what is fixed or changed
I have added validation to the resource form.

Implemented email validation (Gives error on giving wrong mail)
Implemented URL validation (Gives error on giving wrong URL)
Implemented date validation (Gives error on giving date of incorrect date)
Required validation implemented on:
(I) Name
(ii) Email
(iii) Resource URL
(iv) Level of trust
(v) Date
I have used joi-browser for its implementation

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari  I think there is some error.
Small changes like changing != to !== is also failing
image

**Comment by garvitgupta13** [comment]
Found something on stackoverflow. I will try this and get back to you
[Link](https://stackoverflow.com/questions/55271798/browserslist-caniuse-lite-is-outdated-please-run-next-command-npm-update-cani)

**Comment by Kajol-Kumari** [comment]
> Found something on stackoverflow. I will try this and get back to you
> [Link](https://stackoverflow.com/questions/55271798/browserslist-caniuse-lite-is-outdated-please-run-next-command-npm-update-cani)

I think your `package-lock.json` is creating the trouble as it contains some hidden dependency.

**Comment by garvitgupta13** [comment]
> > Found something on stackoverflow. I will try this and get back to you
> > [Link](https://stackoverflow.com/questions/55271798/browserslist-caniuse-lite-is-outdated-please-run-next-command-npm-update-cani)
> 
> I think your `package-lock.json` is creating the trouble as it contains some hidden dependency.

Please look at PR #533

**Pull request closed without merging**
