### PR TITLE
Bug: Reset password fixed 

### PR DESCRIPTION
**Pull request by BHS-Harish**
## Issue that this pull request solves

 Closes: #989 
## Screenshots

https://github.com/user-attachments/assets/656a55de-e1be-4b0c-aba8-052a7b6103d8

### CODE REVIEW

**Comment by BHS-Harish** [comment]
Hey @Kajol-Kumari 

Please review the request :)

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@BHS-Harish 
1. 52 file changes, this pr has a lot of unnecessary changes, can u please clean it?
2. The build is failing please fix it.

**Comment by BHS-Harish** [comment]
> @BHS-Harish
> 
> 1. 52 file changes, this pr has a lot of unnecessary changes, can u please clean it?
> 2. The build is failing please fix it.

When i changed particular file within a folder that shows as the entire folder were changed that is the reason why 52 files were changed

**Comment by Kajol-Kumari** [comment]
> > @BHS-Harish
> > 
> > 1. 52 file changes, this pr has a lot of unnecessary changes, can u please clean it?
> > 2. The build is failing please fix it.
> 
> When i changed particular file within a folder that shows as the entire folder were changed that is the reason why 52 files were changed

You can add particular files only under using `git add <file_path1> <file_path2> ...` instead of doing `git add .` this will avoid any unnecessary file change to come under the pr

**Comment by BHS-Harish** [comment]
Okay let me close the current pr and raise new one

**Pull request closed without merging**
