### PR TITLE
Resource page

### PR DESCRIPTION
**Pull request by urvashi-code1255**
## Issue that this pull request solves
SWOC AND DWOC PARTICIPANT
 Closes: #247 

## Proposed changes

-  Make the top margin small, same as contact-us page
-  Change the pencil icon with the same icon being used in contact-us page
- The calender icon should also have the hovering effect and cursor pointer
- Replace the level of trust checkbox with select box having the placeholder of level of trust
- Put the valid until text under input box only

### Brief description of what is fixed or changed
1. Made the margin same as of the contact us page.
2. Pencil icon is changed.
3. calender icon has cursor pointer and orange color on hover.
4.  Added select box.
5. Added the valid until text under input box only

## Types of changes
Bootstrap, Css, Javascript

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @urvashi-code1255 please do these:
1. Remove the unnecessary changes from this PR
2. select box needs enhancements as it's not looking good. Maybe try to replace it with radio buttons
3. The label `valid until` should be under the input field, similar to other input fields

**Comment by urvashi-code1255** [comment]
> Hey @urvashi-code1255 please do these:
> 1. Remove the unnecessary changes from this PR
> 2. select box needs enhancements as it's not looking good. Maybe try to replace it with radio buttons
> 3. The label `valid until` should be under the input field, similar to other input fields

The label `valid until` should be the place holder for the date input? I didn't understood please clarify @Kajol-Kumari

**Comment by Kajol-Kumari** [comment]
Hey @urvashi-code1255 currently the date field have placeholder of `mm/dd/yyyy` make it `Valid Until: mm/dd/yyyy`

**Comment by urvashi-code1255** [comment]
Okay @Kajol-Kumari

**Comment by urvashi-code1255** [comment]
Capture

@Kajol-Kumari Is this Okay?

**Comment by Kajol-Kumari** [comment]
Hey @urvashi-code1255 just make the radio button and text well aligned and make the values on the right if the radio button and it will be good to go :)

**Comment by urvashi-code1255** [comment]
Capture
@Kajol-Kumari Now?

**Comment by Kajol-Kumari** [comment]
> Capture
> @Kajol-Kumari Now?

@urvashi-code1255 this looks good to go! Please push the code so that I can test it once.

**Pull request closed without merging**
