### PR TITLE
footer_update

### PR DESCRIPTION
**Pull request by vedikaag99**
## Issue that this pull request solves

 Closes: # (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by vedikaag99** [comment]
https://user-images.githubusercontent.com/67699840/103088478-00fe8280-4611-11eb-9b93-40f4cf00460e.mov

**Review by Kajol-Kumari — COMMENTED** [review]
Just remove the `.DS_store` file from this PR. Rest LGTM :)

You can use `git checkout HEAD -- .DS_Store` for removing this file from this commit. For more detail, check out [here](https://stackoverflow.com/questions/7147270/hard-reset-of-a-single-file)

**Comment by vedikaag99** [comment]
Done. Please check if it is done :)

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Pull request merged**
