### PR TITLE
fixed the select domain button for light theme

### PR DESCRIPTION
**Pull request by Stiffpixels**
## Issue that this pull request solves

 Closes: #879 

### Brief description of what is fixed or changed
- fixed the look of select domain input control in light mode.
- fixed the transparent background of the select panel in light mode.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Video of the fix

https://github.com/HITK-TECH-Community/Community-Website/assets/32983571/84de4ffa-9409-44bc-b426-039c2356cb3f

### CODE REVIEW

**Comment by Stiffpixels** [comment]
@Kajol-Kumari  requesting a review from you.

**Review by Kajol-Kumari — APPROVED** [review]
Nice and Clean !
LGTM 👍

**Comment by Kajol-Kumari** [comment]
Hi @Stiffpixels We have similar issue under the addTeam form of admin panel, can you fix there as well? Feel free to open a new issue for the same. 
Screenshot 2024-05-15 at 8 32 02 PM

**Comment by Stiffpixels** [comment]
> Hi @Stiffpixels We have similar issue under the addTeam form of admin panel, can you fix there as well? Feel free to open a new issue for the same. 
> Screenshot 2024-05-15 at 8 32 02 PM
> 

For sure will get back to you with the issue tomorrow.

**Pull request merged**
