### PR TITLE
Issue #11 UI for Resource_Sharing_Form

### PR DESCRIPTION
**Pull request by Sapphire-Skies**
Resource_Sharing_Form

Added the figma link in Readme.md

### CODE REVIEW

**Comment by Sapphire-Skies** [comment]
[https://www.figma.com/file/sh8ubRJgEXtQRbxCiJ3b48/Untitled?node-id=4%3A13](url)

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @Sapphire-Skies please keep the url of the figma design only in this PR and revert the other changes

**Review by Sapphire-Skies — COMMENTED** [review]
Reverted all the changes back as instructed!

**Comment by Kajol-Kumari** [comment]
> Reverted all the changes back as instructed!

Hey @Sapphire-Skies You can simple use `git checkout HEAD -- my-file.txt` for reverting any file change. For more detail checkout [here](https://stackoverflow.com/questions/7147270/hard-reset-of-a-single-file) It will revert the particular file change and you won't need to do it manually :)

**Pull request closed without merging**
