### PR TITLE
Added dark mode to get involved and privacy policy pages

### PR DESCRIPTION
**Pull request by FireQueen-3010**
## Issue that this pull request solves

Part of: #490

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

image
image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review @Kajol-Kumari :)

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @FireQueen-3010 the changes indeed looking good but in card mode it's hard to recognise the card of the `get-involved` page. Maybe if we can provide the box shadow all over the card(just for the dark mode, then it will look better) WDYT?

**Comment by Kajol-Kumari** [comment]
> Hey @FireQueen-3010 the changes indeed looking good but in card mode it's hard to recognise the card of the `get-involved` page. Maybe if we can provide the box shadow all over the card(just for the dark mode, then it will look better) WDYT?

Or maybe you can add a border to the cards just like @Coder-Srinivas has done for the `all-broadcasts` page

**Comment by FireQueen-3010** [comment]
Made the required changes @Kajol-Kumari , please review :)

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for fixing it quickly @FireQueen-3010 :)
LGTM :+1:

**Pull request merged**
