### PR TITLE
Editmodal dark theme

### PR DESCRIPTION
**Pull request by garvitgupta13**
## Issue that this pull request solves

 Closes: #658 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @garvitgupta13 Thanks for taking time to fix it. Can you please enhance the button look of the modal along with enhancement in it's heading maybe similar to the filter buttons of the page

**Comment by garvitgupta13** [comment]
image
I am unable to login, is there any change from your side

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 Thanks for taking time to fix it. Can you please enhance the button look of the modal along with enhancement in it's heading maybe similar to the filter buttons of the page

image
Hey @Kajol-Kumari is this fine, if you want any other changes then please let me know

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 can we please try some different look for the `Edit` button as the current one isn't looking legit

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 can we please try some different look for the `Edit` button as the current one isn't looking legit

Please let me know which type of changes you want, should I try some different colour, font or change its dimension.

**Comment by Kajol-Kumari** [comment]
> > Hey @garvitgupta13 can we please try some different look for the `Edit` button as the current one isn't looking legit
> 
> Please let me know which type of changes you want, should I try some different colour, font or change its dimension.

Hey @garvitgupta13  Please do the following 
1. the top and bottom padding of the button needs to be increased a bit
2. The width of the button needs to be reduced
3.  The look of the button can be made similar to the `submit` button of other forms with the size a bit smaller as per the requierement here?

**Comment by garvitgupta13** [comment]
> > > Hey @garvitgupta13 can we please try some different look for the `Edit` button as the current one isn't looking legit
> > 
> > 
> > Please let me know which type of changes you want, should I try some different colour, font or change its dimension.
> 
> Hey @garvitgupta13 Please do the following
> 
> 1. the top and bottom padding of the button needs to be increased a bit
> 2. The width of the button needs to be reduced
> 3. The look of the button can be made similar to the `submit` button of other forms with the size a bit smaller as per the requirement here

image
Hey @Kajol-Kumari is this fine, if you want any other changes then please let me know

**Review by Kajol-Kumari — COMMENTED** [review]
Hey @garvitgupta13 thanks for taking the accountability to fix this issue. The button's UI is now looking way better. See if you can make the edit modal form's look similar to what we have in other forms. But it's totally up to you :)

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 thanks for taking the accountability to fix this issue. The button's UI is now looking way better. See if you can make the edit modal form's look similar to what we have in other forms. But it's totally up to you :)

Please let me know which type of changes you want with the form, if they are small changes I will try to fix them.

**Comment by Kajol-Kumari** [comment]
> > Hey @garvitgupta13 thanks for taking the accountability to fix this issue. The button's UI is now looking way better. See if you can make the edit modal form's look similar to what we have in other forms. But it's totally up to you :)
> 
> Please let me know which type of changes you want with the form, if they are small changes I will try to fix them.

I will open up a separate issue for that as it won't be a small change

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari please add the necessary gssoc labels

**Comment by Kajol-Kumari** [comment]
> Hey @Kajol-Kumari please add the necessary gssoc labels

Hey @garvitgupta13 as gssoc ended on 31st only, we won't be able to add any label for this pr

**Comment by garvitgupta13** [comment]
> > Hey @Kajol-Kumari please add the necessary gssoc labels
> 
> Hey @garvitgupta13 as gssoc ended on 31st only, we won't be able to add any label for this pr

As per gssoc PR opened on or before 3st and merged on or before 5 June will be counted

**Comment by garvitgupta13** [comment]
> As per gssoc PR opened on or before 31st may and merged on or before 5 June will be counted
> image

Hey @Kajol-Kumari please have a look at it

**Comment by jackfrost13** [comment]
@Kajol-Kumari Please add the level

**Pull request merged**
