### PR TITLE
Carousel Update

### PR DESCRIPTION
**Pull request by urvashi-code1255**
## Issue that this pull request solves
(SWOC AND DWOC Participant)
 Closes: #232 

## Proposed changes
* Add padding on top and bottom of the section
*  Fix the carousel navigation buttons. Make sure the chevron icon is vertically centre aligned.
* Fix the mobile view as the cards look very small when viewed on the mobile device.

### Brief description of what is fixed or changed
*  Added padding on top and bottom of the section
*  Fixed the carousel navigation buttons.
*  Fixed the mobile view as the cards look very small when viewed on the mobile device.

## Types of changes
Frontend CSS, Bootstrap 4

_Put an `x` in the boxes that apply_
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by urvashi-code1255** [comment]
@salil-naik Please review :)

**Comment by salil-naik** [comment]
@urvashi-code1255 have you pushed all your changes? I can see that only 4 lines are changed.

**Comment by urvashi-code1255** [comment]
@salil-naik actually on the new branch carousel I have created most of the things were looking fine. So I changed only 4 lines and it worked at my end. Please check if it's working on your end too

**Comment by salil-naik** [comment]
@urvashi-code1255 changes aren't reflected on my end. Have you pulled the latest changes from the main/master branch?

**Comment by urvashi-code1255** [comment]
@salil-naik Okay let me see

**Comment by mohit355** [comment]
Also include some SnapShots

**Comment by urvashi-code1255** [comment]
@kenkirito will do it. Sorry for the inconvinience. I m closing this PR

**Pull request closed without merging**
