### PR TITLE
[Frontend] Implement Broadcast page Design #53

### PR DESCRIPTION
**Pull request by kenkirito**
## Issue that this pull request solves

 Closes: # (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by kenkirito** [comment]
HITK Tech Community and 25 more pages - Personal - Microsoft​ Edge 30-12-2020 05_37_12 PM

**Comment by kenkirito** [comment]
hii i am not able to make a popup

**Comment by kenkirito** [comment]
i am still trying but merge this page

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @kenkirito please do the following changes:
1. use `#1B2431` color in background of broadcasts
2. Make card with white background and dummy data instead of posters in the carousel
3. make the size of the broadcasts bigger(atleast 80-90vh)

**Comment by kenkirito** [comment]
ok

**Comment by kenkirito** [comment]
i have done the changes that you ask for

**Comment by kenkirito** [comment]
i will summit it by midnight

**Comment by Kajol-Kumari** [comment]
closing this due to duplication

**Pull request closed without merging**
