### PR TITLE
Success card on password change

### PR DESCRIPTION
**Pull request by garvitgupta13**
## Proposed changes
Added a success card on successful password change
## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by garvitgupta13** [comment]
Please add the necessary `gssoc21` labels

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 the Card UI seems kinda inconsistent.  Can you please try implementing somewhat similar to the below card UI
Screenshot from 2021-03-27 11-44-48

**Comment by garvitgupta13** [comment]
Is this design fine
image

**Comment by Kajol-Kumari** [comment]
> Is this design fine
> image

Hey @garvitgupta13 yeah, this :top: looks fine. Please push the changes in here

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for the quick fix @garvitgupta13 
LGTM :+1:

**Pull request merged**
