### PR TITLE
Updating issue templates

### PR DESCRIPTION
**Pull request by SHITIZ-AGGARWAL**
## Issue that this pull request solves

 Closes: #42 

## Proposed changes

Added bug report and feature request issue templates

### Brief description of what is fixed or changed

Added bug report and feature request issue templates

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
can we please have a short message in commented form like `Thank you for taking time to report this issue` and similarly for feature request as well

**Comment by SHITIZ-AGGARWAL** [comment]
Where should I add the comment ,In the beginning or in the end?

**Comment by Kajol-Kumari** [comment]
> Where should I add the comment ,In the beginning or in the end?

In the beginning

**Review by Kajol-Kumari — APPROVED** [review]
@SHITIZ-AGGARWAL thanks for incorporating the suggested changes! 
LGTM 👍

**Comment by Kajol-Kumari** [comment]
@all-contributors please add @SHITIZ-AGGARWAL for doc

**Pull request merged**
