### PR TITLE
Update gitignores

### PR DESCRIPTION
**Pull request by hazemessam**
## Proposed changes

- Add backend/.gitignore
- Ignore backend/uploads/ that is get generated when running the tests locally
- Unignore backend/package-lock.json for clean install

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

### CODE REVIEW

**Comment by hazemessam** [comment]
@Kajol-Kumari Please, check this PR under GSSoC22.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari Please, check this PR under GSSoC22.

Can you please help me understand the need of this pr? As now you have even removed `package-lock.json` from the gitignore file

**Comment by hazemessam** [comment]
> > @Kajol-Kumari Please, check this PR under GSSoC22.
> 
> Can you please help me understand the need of this pr? As now you have even removed `package-lock.json` from the gitignore file

In the `Dockerfile` we will need the `package-lock.json`  file to run `npm ci` instead of `npm install` which will install the exact packages versions instead of upgrading it

Ref: https://www.youtube.com/watch?v=7lYnzRkVVLE

**Comment by hazemessam** [comment]
> > > @Kajol-Kumari Please, check this PR under GSSoC22.
> > 
> > 
> > Can you please help me understand the need of this pr? As now you have even removed `package-lock.json` from the gitignore file
> 
> In the `Dockerfile` we will need the `package-lock.json` file to run `npm ci` instead of `npm install` which will install the exact packages versions instead of upgrading it
> 
> Ref: https://www.youtube.com/watch?v=7lYnzRkVVLE

That will reduce the incompatibility bugs.

**Comment by hazemessam** [comment]
@Kajol-Kumari Any updates?

**Comment by Kajol-Kumari** [comment]
Hey @hazemessam we should never keep `package-lock.jsob` in the repo. Also if you want to avoid version upgrade during installation of packages, just remive `^` from the version name. I really don't find the need if this pr and hence request you to close it. 

In order to avoid the effort waste, always raise an issue first, get assigned and then start working on that issue.

**Pull request closed without merging**
