### PR TITLE
join us form fixed

### PR DESCRIPTION
**Pull request by vedikaag99**
This PR is under DWoC.

## Issue that this pull request solves

 Closes: #337 (issue number)

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

https://user-images.githubusercontent.com/67699840/107510690-5ba46b80-6bca-11eb-97a4-3927178dd953.mov

## Other information

After pulling the latest changes, the join us form was totally distorted so I fixed some additional things apart from the deliverables mentioned in the issue like the icons on hover weren't changing colour, alignment of the input fields and so on. @Kajol-Kumari please review now.

### CODE REVIEW

**Review by tejan-singh — CHANGES_REQUESTED** [review]
Nice work. 
- Please also add **required** message when form submitted below each field.
- Please align **Interested Domain** items

**Comment by vedikaag99** [comment]
> Nice work.
> 
> * Please align **Interested Domain** items

Umm @Kajol-Kumari had asked me to align them row-wise just like in this PR. What changes do I need to make?

**Comment by tejan-singh** [comment]
> 
> 
> > Nice work.
> > 
> > * Please align **Interested Domain** items
> 
> Umm @Kajol-Kumari had asked me to align them row-wise just like in this PR. What changes do I need to make?

I mean like this 
Checkbox-Field

**Comment by vedikaag99** [comment]
Screen Shot 2021-02-11 at 12 37 57 AM
@tejan-singh done

**Review by tejan-singh — CHANGES_REQUESTED** [review]
- Please align for responsive website also
Capture

**Comment by vedikaag99** [comment]
@tejan-singh done. please check now.
Screen Shot 2021-02-11 at 4 17 26 PM

**Review by tejan-singh — APPROVED** [review]
Nice Work! 👍🏻

**Comment by vedikaag99** [comment]
@tejan-singh Hi, could please also add the DWOC tag and Level-x tag to this PR so that I can be marked accordingly.

**Pull request merged**
