### PR TITLE
Reduce the button size

### PR DESCRIPTION
**Pull request by amanprateek123**
## Issue that this pull request solves

 Closes: #306 

## Proposed changes
Changing the width of buttons for smaller resolution

### Brief description of what is fixed or changed
Width of the mention buttons in smaller resolution is reduces.
## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
Screenshot from 2021-01-27 13-22-14

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @amanprateek123 can you please check if the button is appearing correctly for all pages including `terms of use`  `peivacy policy`  `resource sharing` etc

**Comment by amanprateek123** [comment]
> Hey @amanprateek123 can you please check if the button is appearing correctly for all pages including `terms of use` `privacy policy` `resource sharing` etc on both small and large screens

@Kajol-Kumari  Done

**Comment by Kajol-Kumari** [comment]
> > Hey @amanprateek123 can you please check if the button is appearing correctly for all pages including `terms of use` `privacy policy` `resource sharing` etc on both small and large screens
> 
> @Kajol-Kumari Done

Seems like you have screwed up while rebasing. I can see a lot of unnecessary commit in this PR. I request you to always navigate to `main` branch before creating a new branch. It won't cause unnecessary commits to come in your PR.

**Comment by amanprateek123** [comment]
@Kajol-Kumari  got it! Actually initially I have some problem with rebasing but now I am cleared.I will resolve the conflicts

**Comment by Kajol-Kumari** [comment]
Hey @amanprateek123 I can still see unnecessary changes in this PR like unnecessary modifications in `resource` component. Please fix them

**Comment by amanprateek123** [comment]
@Kajol-Kumari  Fixed

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @amanprateek123 the buttons look fine for small screens but we need smaller width for large screens as well. Please implement the same

**Comment by amanprateek123** [comment]
@Kajol-Kumari  Done

**Comment by Kajol-Kumari** [comment]
@tejan-singh Please test this PR

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Pull request merged**
