### PR TITLE
Enhancement in Edit broadcast modal

### PR DESCRIPTION
**Pull request by amanprateek123**
## Issue that this pull request solves

 Closes: #400 

## Proposed changes
All the requested change in all broadcast page is done
## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by tejan-singh — COMMENTED** [review]
- Please add screenshots of your work for review.

**Comment by amanprateek123** [comment]
Screenshot from 2021-02-20 12-50-16
Screenshot from 2021-02-20 12-50-07
Screenshot from 2021-02-20 12-50-02

**Review by tejan-singh — CHANGES_REQUESTED** [review]
- Please update design for responsiveness. It seems to get squashed

Capture

**Comment by amanprateek123** [comment]
Screenshot from 2021-02-20 15-54-14

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@amanprateek123 please incorporate these:
1. Resolve the conflict
2. Provide border-radius of 8px to the edit modal card. 
3. In the input fields, when the text goes longer than the provided field, please break it to go to the next line
4. The edit button needs enhancement(maybe use one from the buttons present in `util`)

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Pull request merged**
