### PR TITLE
Added login page design in the folder loginPage - VaishnaviShah

### PR DESCRIPTION
**Pull request by vaishnavirshah**
## Issue that this pull request solves

 Closes: #99 

## Proposed changes

I have added an image for login page, changed the position of the login section and made it similar to Contact us Page.

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @vaishnavirshah the UI is looking preety good. But it's breaking on smaller screens, Can you please make this responsive so that we can replace it with our current UI. 

Also please let me know under which program you have made this PR

**Comment by vaishnavirshah** [comment]
> Hey @vaishnavirshah the UI is looking preety good. But it's breaking on smaller screens, Can you please make this responsive so that we can replace it with our current UI.
> 
> Also please let me know under which program you have made this PR

I have made it responsive, kindly check that. I have contributed under SWOC

**Comment by Kajol-Kumari** [comment]
@vaishnavirshah the page is still not appearing properly for smaller devices. Can you please check and fix it?

**Comment by vaishnavirshah** [comment]
This is how it looks:

Normal Screen:
image

Iphone X:
image

**Comment by vaishnavirshah** [comment]
> @vaishnavirshah please make your pull request from another branch. Please read the contribution guidelines.

I have made another PR #200  from the branch login-page. I only have basic knowledge of git and GitHub, so let me know if I have made any errors while making branches.

**Comment by Kajol-Kumari** [comment]
> This is how it looks:
> 
> Normal Screen:
> image
> 
> Iphone X:
> image

The image shouldn't disappear, instead should appear above the form.

**Comment by tejan-singh** [comment]
> 
> 
> > @vaishnavirshah please make your pull request from another branch. Please read the contribution guidelines.
> 
> I have made another PR #200 from the branch login-page. I only have basic knowledge of git and GitHub, so let me know if I have made any errors while making branches.

@vaishnavirshah You made branch correctly. Nice Work.

**Pull request closed without merging**
