### PR TITLE
carousel css converted to carousel.module.css

### PR DESCRIPTION
**Pull request by ashuvssut**
## Issue that this pull request solves
carousel css converted to carousel.module.css

adds to #349

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@ashuvssut the changes looks good to me. Can you please resolve the conflict so that we can merge this

**Comment by ashuvssut** [comment]
@Kajol-Kumari, I have participated in DWoC and SWoC

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari, I have participated in DWoC and SWoC

Can you please fix the conflict.

**Comment by ashuvssut** [comment]
@Kajol-Kumari please review. I have fixed this second merge conflict.

**Pull request merged**
