### PR TITLE
converted css to css modules: section2

### PR DESCRIPTION
**Pull request by ashuvssut**
## Issue that this pull request solves

adds to solving #349

## Proposed changes
converted css to css modules of section2
- 404.css
- about_us.css
- Login.css
- contact_us.css

- [x] New feature (non-breaking change which adds functionality)

_-- I am a DWoC and SWoC participant_

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @ashuvssut the `about-us` page got distorted due to the changes in this PR. Can you please fix it?

**Comment by ashuvssut** [comment]
Okay

**Comment by ashuvssut** [comment]
pushing changes within a few minutes

**Comment by ashuvssut** [comment]
@Kajol-Kumari , mam which part/section? 

please give the classname of the section in which you see the faulty UI

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari , mam which part/section?
> 
> please give the classname of the section in which you see the faulty UI
> 
> If you want to give a screenshot instead, please provide one

Hey @ashuvssut starting from [here](https://github.com/HITK-TECH-Community/Community-Website/pull/358/files#diff-9958c6ad89b1b3e911d9c693b090eeec60ed73a913d333f27783e309c2b3d465R38) the UI Is getting distorted. I can give you a ss in a while of both the current UI and after UI

**Comment by ashuvssut** [comment]
No thanks, I will check the main branch

**Comment by Kajol-Kumari** [comment]
Before - 
Screenshot from 2021-02-06 13-40-20
Screenshot from 2021-02-06 13-40-23

After - 
Screenshot from 2021-02-06 13-40-44
Screenshot from 2021-02-06 13-40-53
Screenshot from 2021-02-06 13-40-56

**Comment by ashuvssut** [comment]
Okay thanks😅

**Comment by ashuvssut** [comment]
@Kajol-Kumari , like nehaparmar said, owl-carousel needed an extra css file....here in my case MDBBadges need one too. I didn't realize that.🤣

So, I have created that extra css file.🙂

**Comment by ashuvssut** [comment]
@Kajol-Kumari, mam, **I think** SWoC has level labels too, namely `easy`, `medium`, `hard`, `intermediate`.

I am not completely sure. But see this [link](https://github.com/smaranjitghose/doc2pen/pull/447) once. The maintainer of that repo has added a `medium` label in my PR. 

I am not sure because, that `medium` label has no description written about it. I really dont know if SWoC has instructed maintainers to use those 4 labels for their event

**Comment by ashuvssut** [comment]
@Kajol-Kumari, one last question, which linux distro do you use?

and if that distro is not Ubuntu, then can you please tell why you prefer that other distro?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari, mam, **I think** SWoC has level labels too, namely `easy`, `medium`, `hard`, `intermediate`.
> 
> I am not completely sure. But see this [link](https://github.com/smaranjitghose/doc2pen/pull/447) once. The maintainer of that repo has added a `medium` label in my PR.
> 
> I am not sure because, that `medium` label has no description written about it. I really dont know if SWoC has instructed maintainers to use those 4 labels for their event

Hey @ashuvssut it's not mandatory to add all the labels are it's done only for our convenience and we the ultimate person to give you scores. I hope you keep checking your scores regularly on the score-sheets shared by maintainers.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari, one last question, which linux distro do you use?
> 
> and if that distro is not Ubuntu, then can you please tell why you prefer that other distro?

I am using Ubuntu. Btw this isn't the right place to discuss these are always welcomed to take these questions in my dm or in our `general` channel of [slack](https://join.slack.com/t/hitkteckcommunity/shared_invite/zt-jgr1sd87-lhiXHO_x63Kt7h8VBxDaFw)

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @ashuvssut just need few fixes
1. `Join Us` button on home page is getting distorted
2. `Let's Talk` button of contact form is getting misplaced
3. `Go home` button of 404 page is getting distorted

Rest looks nice and clean!

**Review by Kajol-Kumari — APPROVED** [review]

**Pull request merged**
