### PR TITLE
Hero section changes

### PR DESCRIPTION
**Pull request by Swastik1710**
## Issue that this pull request solves - Added a div class container to the hero section.

 Closes: #299 

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
Hero Section

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by Swastik1710** [comment]
I had made the changes yesterday only.
Was just waiting for you to respond.
Kindly consider my PR for this issue @salil-naik 
Thanks.

**Review by salil-naik — CHANGES_REQUESTED** [review]
Hi @Swastik1710 , good job so far. 

Since you have added the container class, there is no need for extra left and right padding that is given to `content` class. 

- [ ] Remove the left and right padding from the content class. 
- [ ] Make sure it follows the grid, that is, the hero section should have the same left and right offset as "Our motives" section and carousel section on the homepage.

**Comment by Swastik1710** [comment]
Sure, I will get back to you after making the changes.

**Comment by Swastik1710** [comment]
Hey @salil-naik , I've made the requested changes. Kindly have a look and do let me know if any further changes are required.

**Review by salil-naik — APPROVED** [review]
Good job!

**Comment by salil-naik** [comment]
@Swastik1710 Are you a swoc or a dwoc participant?

**Comment by Swastik1710** [comment]
Hey  @salil-naik, thanks a lot.
I'm a DWOC participant.

**Pull request merged**
