### PR TITLE
First template

### PR DESCRIPTION
**Pull request by codewithvk**
Issue #3 solved!

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @codewithvk Thanks for the PR.
Can we please have a clean readme having just the instruction of how to run the frontend code.

**Comment by codewithvk** [comment]
@Kajol-Kumari Sure.

**Comment by codewithvk** [comment]
@Kajol-Kumari  can you review it?

**Comment by Kajol-Kumari** [comment]
@all-contributors please add @Kajol-Kumari  for code, eventOrganizing, doc, content, ideas, maintenance, mentoring

**Comment by Kajol-Kumari** [comment]
@all-contributors please add @codewithvk  for code

**Pull request merged**
