### PR TITLE
Update admin

### PR DESCRIPTION
**Pull request by mayank-del**
## Issue that this pull request solves

 Closes: #693 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)

## Checklist

_Put an `x` in the boxes that apply_

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by mayank-del** [comment]
@Kajol-Kumari  , please check it once, i have tested this codes on my local projects, it worked for them

**Review by AyushSingh22 — APPROVED** [review]

**Comment by mayank-del** [comment]
@AyushSingh22 , @Kajol-Kumari  , I think , you should merge this request because i had already tested these files on my local system

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
[question] -
Why do we need a separate schema & validator for "updating". Why can't we use the existing admin schema?

**Comment by mayank-del** [comment]
@Kajol-Kumari maam, actually ,Ip

**Comment by mayank-del** [comment]
@Kajol-Kumari  maam, i did it just because of the fact that reset password ,change password and forgotten password have similar type of codes.So, I do not want to make it complex by using existing schema

**Review by Kajol-Kumari — APPROVED** [review]

**Comment by Kajol-Kumari** [comment]
Adding `level 1` to this pr due to the extra effort that you had to put raising the pr again..

**Pull request merged**
