### PR TITLE
Fixing our motive section

### PR DESCRIPTION
**Pull request by abhay313**
## Issue that this pull request solves

 Closes: #248  (SWoC participant)

## Proposed changes

- [x] On hovering, the whole card content should be white
- [x] Make the icon size a bit smaller

### Brief description of what is fixed or changed
added margins on icons and change color of text on hovering

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Screenshot from 2021-01-12 12-55-34

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by salil-naik — CHANGES_REQUESTED** [review]
Hi @abhay313, good work. 

You can make it look even better if you do the following changes. 
1. Give `padding: 20px` in **.single-features** class. 
2. Remove margin and give `padding-right:18px` in **.features-icon** class

**Comment by abhay313** [comment]
@salil-naik `  padding: 20px 10px;` already added in **.single-features** and  `padding-right:18px` I have added in **.features-icon** 

Screenshot from 2021-01-12 17-34-34

**Comment by salil-naik** [comment]
@abhay313 we need equal padding on all 4 sides. So put `padding:20px`. Remove 10px.

**Comment by abhay313** [comment]
done @salil-naik

**Review by salil-naik — APPROVED** [review]

**Comment by abhay313** [comment]
Screenshot from 2021-01-14 11-24-38

Check it once

**Comment by Kajol-Kumari** [comment]
@abhay313 looks nice and clean just replace the first icon with [this](https://fontawesome.com/icons/bullhorn?style=solid one and it would be good to go!

**Comment by abhay313** [comment]
Screenshot from 2021-01-14 11-57-30
 
Is it fine ?

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for incorporating all the suggested changes
LGTM :+1:

**Pull request merged**
