### PR TITLE
Created a basic backend server

### PR DESCRIPTION
**Pull request by NewCoderBoi**
Created a basic backend server with three routes, the main route ('/') , and a resources route ('/resources') and a 404 error route. Also created the controllers for these routes.

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @NewCoderBoi Can we please have the instruction to run it in the readme file of the `backend` folder. Currently it contains dummy data, instead let's have only the steps to run the backend server.

**Comment by NewCoderBoi** [comment]
Updated the readme file with the steps to run the server.

**Comment by Kajol-Kumari** [comment]
Screenshot from 2020-12-07 21-35-26

Hey @NewCoderBoi I am getting this error while trying to run your code. 
Can you please look at it. Also if you are using node version > 12 please keep it to v12 only.

**Comment by NewCoderBoi** [comment]
Converted all code to run on node v12.

**Comment by Kajol-Kumari** [comment]
@NewCoderBoi Can you please tell me if you made this PR under KWoC?

**Comment by NewCoderBoi** [comment]
Is there any separate procedure to do a PR under KWoC? I have registered for KWoC and created this pull request from the github account with which I registered for it.

**Comment by Kajol-Kumari** [comment]
No, there isn't any procedure in specific, we just want to keep it with specific label to diffrentiate as we would be applying for other open source events as well.

**Comment by Kajol-Kumari** [comment]
@all-contributors please add @NewCoderBoi  for code

**Pull request merged**
