### PR TITLE
Reset password

### PR DESCRIPTION
**Pull request by garvitgupta13**
## Issue that this pull request solves

 Closes: #469

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

- Error on different values of newPassword and Confirm Password

image

- Successfully changed the password from `check` to `check1`
image

- Error messages :
image
image

- Changed the password back to `check`
image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — APPROVED** [review]
Hey @garvitgupta13 The feature is working perfectly fine and the code also looks super nice and clean!
Just a minor enhancement ->(You can make a follow up PR for this :point_down: )
As soon as the password gets changed successfully, let show a card in place of the form saying `You have successfully changed your password`(A better word frame would also work :P)

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 The feature is working perfectly fine and the code also looks super nice and clean!
> Just a minor enhancement ->(You can make a follow up PR for this 👇 )
> As soon as the password gets changed successfully, let show a card in place of the form saying `You have successfully changed your password`(A better word frame would also work :P)
> 
> Please let me know if you can make the followup PR or else I will have to open up an issue for the same

Which type of card you want? Please describe it in detail

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 Something similar to :arrow_down: 
[this](https://user-images.githubusercontent.com/56510414/112461898-71d74700-8d86-11eb-9977-2b6ee2829ca3.JPG) maybe?

**Comment by garvitgupta13** [comment]
Hey @Kajol-Kumari I can do that change.
But just a suggestion from my side that toast message looks better than card.
image
In this card as the persons enters the email he cannot enter another email, to remove that card he need to reload the page.
And if we add a card in the reset password form then once a person will change his password and to change again he will need to reload the page.

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 The thing is after the user has reset his/her password, we don't want to show them the same form and so instead will show them a card. Also we are not doing anything with the toast msg, It will appear as it is. The only thing is after successful change(i.e if there isn't any kind of error), we would replace the form with the card. You can take reference of how we are doing in `Reset Password` feature.

Please let me know if you need any further clarification on this.

**Comment by garvitgupta13** [comment]
> Hey @garvitgupta13 The thing is after the user has reset his/her password, we don't want to show them the same form and so instead will show them a card. Also we are not doing anything with the toast msg, It will appear as it is. The only thing is after successful change(i.e if there isn't any kind of error), we would replace the form with the card. You can take reference of how we are doing in `Reset Password` feature.
> 
> Also it's not a good thing to reset the password frequently so IMO it's totally fine to reload the page if they wish to do so right after the change.
> 
> Please let me know if you need any further clarification on this.


Ok mam, please give me some time, by evening I will go through that feature and will let you know.

**Comment by Kajol-Kumari** [comment]
> > Hey @garvitgupta13 The thing is after the user has reset his/her password, we don't want to show them the same form and so instead will show them a card. Also we are not doing anything with the toast msg, It will appear as it is. The only thing is after successful change(i.e if there isn't any kind of error), we would replace the form with the card. You can take reference of how we are doing in `Reset Password` feature.
> > Also it's not a good thing to reset the password frequently so IMO it's totally fine to reload the page if they wish to do so right after the change.
> > Please let me know if you need any further clarification on this.
> 
> Ok mam, please give me some time, by evening I will go through that feature and will let you know.

Btw feel free to ping me if any clarification is required :)

**Comment by garvitgupta13** [comment]
> > > Hey @garvitgupta13 The thing is after the user has reset his/her password, we don't want to show them the same form and so instead will show them a card. Also we are not doing anything with the toast msg, It will appear as it is. The only thing is after successful change(i.e if there isn't any kind of error), we would replace the form with the card. You can take reference of how we are doing in `Reset Password` feature.
> > > Also it's not a good thing to reset the password frequently so IMO it's totally fine to reload the page if they wish to do so right after the change.
> > > Please let me know if you need any further clarification on this.
> > 
> > 
> > Ok mam, please give me some time, by evening I will go through that feature and will let you know.
> 
> Btw feel free to ping me if any clarification is required :)

Sure mam

**Comment by garvitgupta13** [comment]
Ok mam,

> Hey @garvitgupta13 The feature is working perfectly fine and the code also looks super nice and clean!
> Just a minor enhancement ->(You can make a follow up PR for this 👇 )
> As soon as the password gets changed successfully, let show a card in place of the form saying `You have successfully changed your password`(A better word frame would also work :P)
> 
> Please let me know if you can make the followup PR or else I will have to open up an issue for the same

Hey @Kajol-Kumari I can create a card for that. Should I open a new issue for that ?

**Comment by Kajol-Kumari** [comment]
Hey @garvitgupta13 You can directly come up with a PR and I will suggest you the required changes there only, No need of opening up an issue for the same.

**Pull request merged**
