### PR TITLE
ResourceSharingUi added #11 DWOC

### PR DESCRIPTION
**Pull request by Sshivani-12**
## Issue number #11 

Made Resource Sharing UI using figma

figma link: https://www.figma.com/file/vduLZ69ZtkeJXucuUc2DAK/HITK-Tech-Community?node-id=38%3A2

Resource Sharing 1
resource Sharing 2

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@Sshivani-12 can we please have a legit UI, somewhat similar to `contact us` or `login` page

**Comment by Sshivani-12** [comment]
Okay ,I will work on it.

**Comment by Sshivani-12** [comment]
Made Changes in ResourceSharingPage UI

ResourcePage1 (1)
ResourcePage1 (2)


Figma link:  https://www.figma.com/file/vduLZ69ZtkeJXucuUc2DAK/HITK-Tech-Community?node-id=0%3A1

**Comment by Kajol-Kumari** [comment]
@Sshivani-12 this looks better just make sure to use [this](https://colors.lol/blocky) color pallet and make the form a bit more cleaner. I will be good to go then :)

**Comment by Sshivani-12** [comment]
I have changed the colour as per the pallet and done a few form formating.

ResourcePage1
ResourcePage2


Figma link: https://www.figma.com/file/vduLZ69ZtkeJXucuUc2DAK/HITK-Tech-Community?node-id=0%3A1

**Comment by Kajol-Kumari** [comment]
@Sshivani-12 this looks preety good, just make sure to add this image as well in this PR so that we can use it while implementing it

**Comment by Sshivani-12** [comment]
I have added the same Screenshots in the ResourceSharing folder. I have made a branch named ResourceSharingUI.

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari I have added the same Screenshots in the ResourceSharing folder. I have made a branch named ResourceSharingUI.

Please add the asset image as well in this PR, the image that you have used on the left side of this design

**Comment by Sshivani-12** [comment]
@Kajol-Kumari  yaa I got it! I have added the asset image in that same folder.

**Review by Kajol-Kumari — APPROVED** [review]
@Sshivani-12 Thanks for incorporating the suggested changes. 
LGTM :+1:

**Pull request merged**
