### PR TITLE
contact us UI design

### PR DESCRIPTION
**Pull request by sreechand2002**
Contact us
added the UI design for contact us

### CODE REVIEW

**Comment by theRJMurray** [comment]
you should post a screenshot

**Comment by sreechand2002** [comment]
i have added the screen shot you can check it now

**Review by Kajol-Kumari — COMMENTED** [review]
@sreechand2002 very nice design. Can please revert the other two changes and just keep the screenshot of the image in this PR. Than we can merge this :)

**Comment by sreechand2002** [comment]
i have created the folder now , the other changes happened because i ran the npm script , i doesnt affect anything , now you may check it and merge

**Comment by Kajol-Kumari** [comment]
Hey @sreechand2002 can you please resolve the conflicts here so that we can merge this.

**Pull request closed without merging**
