### PR TITLE
Broadcast update

### PR DESCRIPTION
**Pull request by amanprateek123**
## Issue that this pull request solves

 Closes: #234 

## Proposed changes
- [x] Remove the unnecessary recent broadcast section present at the end of the page
- [x] Fix the card size and make the line break in the form of ellipses(...)
- [x] The ellipses(...) shouldn't be hardcoded
- [x] The modal should show the text of the particular card on which the user will click 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [x] Other (please describe):UI Issue. 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Screenshot from 2021-01-13 15-20-03
Screenshot from 2021-01-13 15-20-08

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by mohit355** [comment]
hey, @amanprateek123  There are some conflicts in your PR with the master branch. please resolve it.


Note:  Alway pull the master branch before making any PR so that your local files and folders are up to date with the remote master branch.

**Comment by amanprateek123** [comment]
@mohit355  got it!

**Comment by amanprateek123** [comment]
@mohit355  please check once again I think I solved the conflict

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @amanprateek123 The changes looks good to me. Just remove this repeated section of recent braodcasts :point_down:  from the page and it will be good to go!
Screenshot from 2021-01-15 18-58-19

**Comment by amanprateek123** [comment]
@Kajol-Kumari  please review it . For any other changes please let me know!

**Comment by Kajol-Kumari** [comment]
> Hey @amanprateek123 The changes looks good to me. Just remove this repeated section of recent braodcasts  from the page and it will be good to go!
> Screenshot from 2021-01-15 18-58-19

@amanprateek123 I guess you missed this! Please remove the second `Recently broadcast` section from the bottom of the page and it will be good to go

**Comment by amanprateek123** [comment]
@Kajol-Kumari  All the changes are completed. Please review it.

**Comment by Kajol-Kumari** [comment]
Hey @amanprateek123 can you please let me know if you are able to run the latest changes of this repository on your local without any error?

**Comment by amanprateek123** [comment]
@Kajol-Kumari  you mean the main repository(with main branch)?

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari you mean the main repository(with main branch)?

Yeah! As I am getting some errors while runing that so just want to confirm if it's only for me

**Comment by amanprateek123** [comment]
@Kajol-Kumari  u r right. There is an error but I resolve it. Someone didn't add the package name in package.json so the package is not installing by "npm i" as it is not mention in package.json file.
I update my PR with this.

This wast the error:-
Screenshot from 2021-01-19 12-10-10

**Comment by Kajol-Kumari** [comment]
> @Kajol-Kumari u r right. There is an error but I resolve it. Someone didn't add the package name in package.json so the package is not installing by "npm i" as it is not mention in package.json file.
> I update my PR with this.
> 
> This wast the error:-
> Screenshot from 2021-01-19 12-10-10

Or you can open up a new PR, I would be happy to assign you marks for this :)

**Comment by amanprateek123** [comment]
@Kajol-Kumari  got it!

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Pull request merged**
