### PR TITLE
Api to delete resource of a given id and delete all resource older than 2months using cron job

### PR DESCRIPTION
**Pull request by Aman16-ai**
## Delete a resource of given id and delete all resources older than 2 months using cron job

 Closes: #738 
### Brief description of what is fixed or changed

- created a route http://localhost:3500/resources/deleteResource to delete a resource corresponding to an id.
- created a cronjob to delete all resource older than 2 months

## Types of changes

_Put an `x` in the boxes that apply_

- [ x] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots
Screenshot (720)
Screenshot (721)
Screenshot (722)
Screenshot (723)
Screenshot (724)

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
We need another api which will take the `resource_id` delete that particular resource under this issue. Please add that as well.

**Comment by Aman16-ai** [comment]
> We need another api which will take the `resource_id` delete that particular resource under this issue. Please add that as well.

I have already implemented it. Please see my commits

**Comment by Kajol-Kumari** [comment]
Hey @Aman16-ai Yeah, I can see both the apis. Could you please add the tests for both of them as well. Then I would give the final review after testing it.

**Comment by Aman16-ai** [comment]
> Hey @Aman16-ai Yeah, I can see both the apis. Could you please add the tests for both of them as well. Then I would give the final review after testing it.

Ok I'll add the tests.

**Comment by Aman16-ai** [comment]
Added test for delete resources
Screenshot (725)
Screenshot (726)
Screenshot (727)

.

**Review by Kajol-Kumari — APPROVED** [review]
LGTM 👍 

@Aman16-ai Can you please resolve the conflict by pulling latest changes from `main` branch so that I can merge it?

**Pull request merged**
