### PR TITLE
Revamped the broadcast section

### PR DESCRIPTION
**Pull request by Coder-Srinivas**
## Proposed changes

Gave a new look to the broadcast section.

1) Added an image to each broadcast. (used the same image appearing in the popup)
2) Have cut down on the description in the the cards.
3) Tuned the dark theme a little.
4) Gave styling to the images using various css properties.

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

image
 
In Dark mode

image

In Light mode

image

Responsive

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @Coder-Srinivas This indeed looking good. Just needs minor enhancements
1. For large screen, the cards seems distorted, please see the GIF attached below for the same.
large_Screen_broadcast

2. The underline in the card(Can you please try removing those undelines as Ig it would look better that way)

**Comment by Coder-Srinivas** [comment]
@Kajol-Kumari I will fix it ASAP.

**Comment by Coder-Srinivas** [comment]
Made the necessary changes.

image

Normal screens

image

Large screens

image

Mobile screens

Please let me know if any changes are required ☺.

**Review by Kajol-Kumari — APPROVED** [review]
@Coder-Srinivas Thanks for incorporating the suggested changes.
LGTM :+1:

**Pull request merged**
