### PR TITLE
added scrollbar in broadcasts

### PR DESCRIPTION
**Pull request by satcasm**
## Issue that this pull request solves

 Closes: #570 

### Brief description of what is fixed or changed

Added missing scrollbar in Broadcasts

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Please attach the screenshots of the changes made in case of change in user interface
image

## Other information

NA

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @satcasm can we please remove that black scroll which appears to be constant? Attaching the screenshot for your reference -

Screenshot 2021-05-01 at 12 12 32 PM

**Comment by satcasm** [comment]
> Hey @satcasm can we please remove that black scroll which appears to be constant? Attaching the screenshot for your reference -
> 
> Screenshot 2021-05-01 at 12 12 32 PM

@Kajol-Kumari I think that is the width in between which the scroll bar occurs, I don't think we can remove that , I might be able to reduce it's width do you want me to do that?

**Comment by Kajol-Kumari** [comment]
Hey @satcasm if we can't remove it, can we please override it's css for dark and light theme in such a way that it seems to be disappeared?

**Comment by satcasm** [comment]
Sure, will give it a shot.

**Comment by satcasm** [comment]
Hey @Kajol-Kumari , is this fine now? I was able to remove that black scroll and also changed the color to match with the original scroll of the page.
image

**Comment by Kajol-Kumari** [comment]
Hey @satcasm this looks pretty good now. Can you please push the change sin this PR?

**Comment by satcasm** [comment]
@Kajol-Kumari  have a review .
THanks!

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for the fix @satcasm 
LGTM 👍

**Pull request merged**
