### PR TITLE
[Frontend] All Broadcasts Page #288

### PR DESCRIPTION
**Pull request by kenkirito**
## Issue that this pull request solves

 Closes: #288 

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] My changes does not break the current system and it passes all the current test cases.

done
home

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by kenkirito** [comment]
@Kajol-Kumari review

**Comment by Kajol-Kumari** [comment]
@kenkirito onhover color seems to be different. Please make it same as `get involved` page

**Comment by kenkirito** [comment]
Ok

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @kenkirito please make a new folder under `broadcast` named as `all-broadcast` put all your all broadcasts related code in there. Also I request you to comment the already present button on the `broadcasts` page and put your `view` button below that

**Comment by kenkirito** [comment]
@Kajol-Kumari I have commented out my button at the end to resolve the merge conflict. please review the code

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Pull request merged**
