### PR TITLE
Creating two endpoints for fetching all questions and question by an id

### PR DESCRIPTION
**Pull request by Aman16-ai**
## Issue that this pull request solves

 Closes: #728

### 

- Created two routes
- http://localhost:3500/question/getallquestions for fetching all questions from db
- http://localhost:3500/question/getQuestionById for fetching a question by an Id

## Types of changes

_Put an `x` in the boxes that apply_

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] My changes does not break the current system and it passes all the current test cases.

## Screenshots

Screenshot (715)
Screenshot (716)
Screenshot (717)
Screenshot (718)
Screenshot (719)

Please attach the screenshots of the changes made in case of change in user interface

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@Aman16-ai I can see the changes from previous pr in this pr. Can we please get rid of all those and just keep the relevant changes in here?

**Comment by Aman16-ai** [comment]
> @Aman16-ai I can see the changes from previous pr in this pr. Can we please get rid of all those and just keep the relevant changes in here?

Now i have removed all previous commit.

**Review by Kajol-Kumari — APPROVED** [review]
Nice&Clean!

LGTM 👍

**Comment by Aman16-ai** [comment]
> Nice&Clean!
> 
> LGTM +1

Thank you 😊

**Comment by Aman16-ai** [comment]
Can u please mention the labels 😅

**Pull request merged**
