### PR TITLE
Converted scss to module.css and fixed menu icon

### PR DESCRIPTION
**Pull request by LeeRenJie**
## Issue that this pull request solves

 Closes: #399 

## Proposed changes
- [x] Convert navbar.scss to navbar.module.css
- [x] The menu bar icon isn't appearing for small screen, please fix it.

### Brief description of what is fixed or changed
- Converted scss file into module.css
- Fixed menu bar icon showing after width=850px 

## Types of changes

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [d] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshots
image

## Other information
When Icon is pressed, the nav-items are distorted
image

Any other information that is important to this pull request

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Hey @LeeRenJie I can see a lot unnecessary changes in this PR can you please remove them.

**Comment by LeeRenJie** [comment]
> Hey @LeeRenJie I can see a lot unnecessary changes in this PR can you please remove them.

Which part specifically? I added some space in some files and fixed some typo, i also added the dependencies for the new version of font-awesome, converted scss to module.css, deleted css file.

**Comment by Kajol-Kumari** [comment]
> converted scss to module.css, deleted css file.

I request you to keep only this PR related changes in here and also let's keep `navbar.module.scss` intead of `navbar.module.css`(just name changing thing)

**Comment by LeeRenJie** [comment]
image

**Review by Kajol-Kumari — APPROVED** [review]
Thanks for incorporating the suggested changes @LeeRenJie 
LGTM :+1:

**Pull request merged**
