### PR TITLE
Refactoring dashboard contact us component

### PR DESCRIPTION
**Pull request by sarthu210**
## Proposed changes
A mobile size problem occurred for the Contact Us card so used CSS VW width size parameter so it can auto fix its size 

## Types of changes

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] My changes does not break the current system and it passes all the current test cases.

## Screenshot

Before:

image

After:

image

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Screenshot 2024-05-23 at 3 02 59 PM

For few screens, the card is appearing left aligned, can we make it centered aligned as well?

**Comment by sarthu210** [comment]
> Screenshot 2024-05-23 at 3 02 59 PM
> For few screens, the card is appearing left aligned, can we make it centered aligned as well?

sure I will make those changes by tomorrow night

**Comment by sarthu210** [comment]
hello mam i resolve the issue by centering the items !

screenshot:
image

**Review by Kajol-Kumari — APPROVED** [review]
the left margin is a little more than right one but should be fine

**Pull request merged**
